### ISSUE TITLE
How can i use "oldSong" in "songChanged" event?

### ISSUE THREAD

**Issue by 4Lajf** [SushiBtw/discord-music-player#108]
so there is the "oldSong" in 
```    .on('songChanged', (message, newSong, oldSong) =>
```
and I'm wondering how can I use it because no matter what I do it always is undefined.

**Comment by SushiBtw** [comment]
**I fixed your issue and I will be pushing the update to NPM in ~4 hours.**
I will let you know, thanks for reporting!

**Comment by SushiBtw** [comment]
Hey! Update time!
I hope everything got fixed, please check within `v7.1.0` and let me know if the error still exists!
https://www.npmjs.com/package/discord-music-player

Thanks for reporting,
Sushi!
