### ISSUE TITLE
Queue remove function not working

### ISSUE THREAD

**Issue by SwixDevs** [SushiBtw/discord-music-player#11]
Hello! Sorry I'm back here I have a problem.
The queue remove command [remove](https://www.npmjs.com/package/discord-music-player#removel) is not working. I have written the exact code that's written at the npm site but it doesn't work!

It says that it has skipped a song from the queue but it hasn't actually done anything.
It also still shows up in the queue command.

I have made some little changes, but it wasn't working anyways when I didn't make the changes

Here's the code if you need it

`     run: async(client, message, args) => {
         
        try{
            client.player.remove(message.guild.id, args[0])
            message.channel.send('Song removed from the queue!')
        }catch(error){
            
            if(error == "Not playing"){
                message.channel.send('Not playing any songs right now, do `-play` to play a song!')
            }
        }
     }`

**Comment by SushiBtw** [comment]
Are you sure, the ``args[0]`` is a int? Please use ``parseInt(args[0])`` for it.

Also, the ``Player#remove(message.guild.id, 0)`` would delete the 1st song from the queue.

**Comment by SwixDevs** [comment]
Thanks a lot, it worked, sorry for my silly mistake.
