### ISSUE TITLE
[FR] Ability to add songs to the front of the queue

### ISSUE THREAD

**Issue by 4Lajf** [SushiBtw/discord-music-player#111]
**Is your feature request related to a problem? Please describe.**
I tried to do `back` command that would play the previous song but I can't do that on current framework without destroying the entire queue. It would be also useful for a `playnow` command when you liteally add a song to the front of a queue.

**Describe the solution you'd like**
Requested song gets added to the front of the queue.

**Describe alternatives you've considered**
I don't think there are any alt ways to do this.

**Additional Comments**
I think this FR is self-explanatory.

Have a great day.

**Comment by SpeckyYT** [comment]
The play() method instantly plays a song.
The addToQueue() method has an option where you can insert any song in any index of the queue (1 = next song). I don't remember how that option is named, but just check for it.

**Comment by SpeckyYT** [comment]
```js
const options = {
    search: "despacito",
    index: 1, // next song
}
player.addToQueue(msg, options)
```

**Comment by ZinMain** [comment]
i managed to create move song command should i share it here?

**Comment by 4Lajf** [comment]
Would be great

**Comment by SpeckyYT** [comment]
wtf
