### ISSUE TITLE
Seek [BUG]

### ISSUE THREAD

**Issue by warmpigman** [SushiBtw/discord-music-player#113]
**Bug Description**
When using seek, no errors return but music stops.

**Reproduction Steps**
Start playing a song, seek a moment in the song.

**Expected Result**
The bot would start playing a moment in the song

**Versioning:**
 - OS: Windows 10 pro, 20H2
 - NPM Version 7.5.2
- Module Version 7.1.1

**Comment by SushiBtw** [comment]
I can not reproduce this issue, can you provide your code so I can look into it?

**Comment by warmpigman** [comment]
const Discord = require('discord.js')
        const sourceFile = require('../../../Steel');
        const { Utils } = require('discord-music-player')
        let time = Utils.TimeToMilliseconds(arguments[0])
        let song = await sourceFile.MusicPlayer.seek(message, parseInt( time * 1000)).catch(err => {
          message.reply('There was an error :(')
            return console.log(err);
        })
        Embed = new Discord.MessageEmbed()
        .setColor('#0099ff')
        .setTitle('Goto moment')
        .setImage('')
        .setTimestamp()
        .setDescription(``)
        .addFields(
              {name:`Went to ${Utils.MillisecondsToTime(time) }`, value:`Of song: ${song.name}`}
        )
        .setFooter(message.author.username + ' | Steel', message.author.displayAvatarURL({dynamic: true}))
        message.channel.send({
            embed: Embed,
            disableMentions:'all'
        })

**Comment by SushiBtw** [comment]
Should be fixed in latest version, can you still reproduce it?
