### ISSUE TITLE
[BUG] leaveOnEmpty is always true even if you set it to false

### ISSUE THREAD

**Issue by Z3T4C0DE** [SushiBtw/discord-music-player#115]
Title says it all. This error occurred when I updated my module.

**Comment by SushiBtw** [comment]
Can reproduce on latest v7.1.3. Working on a fix, thanks for the report.

**Comment by SushiBtw** [comment]
Hey, fixed on https://www.npmjs.com/package/discord-music-player/v/7.1.4!

Thanks for the report.
