### ISSUE TITLE
Typescript Error [BUG]

### ISSUE THREAD

**Issue by Titivoot** [SushiBtw/discord-music-player#118]
**Bug Description**
I can't use discord-music-player with Typescript.

**Attachments**
![Screenshot_2021-04-25-19-22-52-11](https://user-images.githubusercontent.com/20519084/115993269-43a28c80-a5fc-11eb-85d9-adb3f33b5233.jpg)
![Screenshot_2021-04-25-11-02-28-63](https://user-images.githubusercontent.com/20519084/115993273-48ffd700-a5fc-11eb-9d1a-c943c17b50ec.jpg)

**Versioning:**
 - OS: Debian 10
 - NPM Version 7.8.0
- Module Version v7.1.4

**Comment by SpeckyYT** [comment]
The error indicates that the typings don't match the actual content. It's hard to make a module which fetches data which may be missing. Not sure if it's possible to ignore such errors on TypeScript.

**Comment by Titivoot** [comment]
I am using // @ ts-ignore above the line with a bug and it works.

**Comment by SushiBtw** [comment]
Will be fixed in next release tomorrow, thanks for the #119.

**Comment by greysilly7** [comment]
More fixes should be in #121

**Comment by SushiBtw** [comment]
Going live today.
