### ISSUE TITLE
Url doesnt work

### ISSUE THREAD

**Issue by needhelp11** [SushiBtw/discord-music-player#12]
It doesn't work when I want to request a song with url but it doesn't show in any error

**Comment by SushiBtw** [comment]
Hello, we are working on a fix for it. It will get out in few days.

This issue would be resolved in #13.

**Comment by SushiBtw** [comment]
**This issue was resolved in [v6.0.0 Update](https://www.npmjs.com/package/discord-music-player/v/6.0.0).**

Thank you for reporting it.
