### ISSUE TITLE
Unavailable video in a playlist causes bot to return Invalid Playlist

### ISSUE THREAD

**Issue by LyrasaurusRose** [SushiBtw/discord-music-player#127]
If I have a playlist that has an unavailable video (ex private, removed, copyright) the bot will not add the playlist to the queue, and instead return `Error: Unhandled error. ('InvalidPlaylist')`

I would love/appreciate if the framework would just skip the unavailable video and add the rest to the queue. 

It was driving me crazy that I couldn't figure out why I couldn't add this one playlist, since youtube just hides and skips unavailable videos by default.

**Comment by SushiBtw** [comment]
Working on a fix as I can reproduce it.

**Comment by SushiBtw** [comment]
This issue was resolved in v7.2.1.
