### ISSUE TITLE
error: Cannot read property 'voice' of undefined [BUG]

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#128]
**Bug Description**
When I run the 'play' command I get this error: Cannot read property 'voice' of undefined
                                                                            at Player.play (/app/node_modules/discord-music-player/src/Player.js:68:42)

**Reproduction Steps**
I started up my bot on Heroku and then I use the 'play' command I got the error

**Expected Result**
I expected the bot to join the channel and play the music

**Attachments**
![Screenshot (16)](https://user-images.githubusercontent.com/68092869/117560225-1c08f500-b0cf-11eb-84cf-3ec1dc8e8e55.png)

**Versioning:**
 - NPM package 7.1.4
 - Node v. 12 or higher
 
**Additional Comments**
The NPM package worked well before I don't know why it doesn't work now!
I also use **Heroku** as a way of hosting my bot 24/7

**Comment by SpeckyYT** [comment]
It means that the user isn't in a voice channel.
