### ISSUE TITLE
[FR] songs search method

### ISSUE THREAD

**Issue by SpeckyYT** [SushiBtw/discord-music-player#129]
**Is your feature request related to a problem? Please describe.**
Currently there is no "search" method. It could return 10 (or any number in the options) songs and then you can insert the song into the play function (maybe trough a "Song" class (`options.song instanceof Song`, idk)

**Describe the solution you'd like**
```js
const songs = await Util.searchSongsByName('despacito', {max: 10});
const song = await functionWhichLetsTheUserSelectASong(songs); // this is on our side
client.player.play(msg, { song: song });
```
or something

**Describe alternatives you've considered**
Nah, it's fine

**Additional Comments**
Amogus

**Comment by SushiBtw** [comment]
Working on it now :)

**Comment by SushiBtw** [comment]
You can now use `search()` method via Utils in the `dev` build!
How to install it? Check #177.

How to use the `search()` method?
```js
const { Player, RepeatMode, Utils } = require("discord-music-player");
let songLimit = 10;
Utils.search('never gonna give you up', {}, queue, songLimit)
```
![image](https://user-images.githubusercontent.com/45533122/129802807-6d4d116d-2e3c-4f67-aa10-4f0756597ff3.png)
