### ISSUE TITLE
[BUG]Connection not established within 15 seconds.

### ISSUE THREAD

**Issue by valseftw** [SushiBtw/discord-music-player#131]
to search for music play (musicname)
I write but throws such an error.
Connection not established within 15 seconds.

**Comment by SpeckyYT** [comment]
I used to have this error too, but I don't remember exactly what was the issue...
But if I should guess the reason, it may have to do with object-prototype pollution.

**Comment by SushiBtw** [comment]
Please check https://github.com/discordjs/discord.js/issues/2979 as it's a djs issue.
