### ISSUE TITLE
[FR] Lyrics feature

### ISSUE THREAD

**Issue by CeaserPlayz** [SushiBtw/discord-music-player#133]
**Is your feature request related to a problem? Please describe.**
I have been trying to make a reliable and good lyrics command. I've tried at least 3 different npm packages for my lyrics command, but due to the song names (eg. "Ashnikko - Slumber Party (ft. Princess Nokia) [Official Music Video]") the package isn't able to find the song or returns the wrong song.

**Describe the solution you'd like**
Some sort of method like song.lyrics() or anything like that.

**Describe alternatives you've considered**
Using other packages and then using song.name to get the lyrics from the package. (eg. getLyrics(song.name)).

**Additional Comments**
If you need me to clarify further, please do tell me. I'm also currently using the [genuis-lyrics](https://www.npmjs.com/package/genius-lyrics) package for my lyrics command.

**Comment by SushiBtw** [comment]
Good FR, I will need to look into this feature.

**Comment by SushiBtw** [comment]
Won't be adding lyrics() method sadly. Too hard to make on that will work on each song.
