### ISSUE TITLE
[BUG] Age restricted videos crashes bot.

### ISSUE THREAD

**Issue by CeaserPlayz** [SushiBtw/discord-music-player#135]
**Bug Description**
Self explanatory. My friend decided to play an age restricted video and it ended up crashing the bot. I've tried to .catch the error, but it still crashes.

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Play an age restricted video. (YouTube)

**Expected Result**
The player to return some kind of error or play the video. Returning an error is most reasonable.

**Attachments**
![image](https://user-images.githubusercontent.com/66173114/119194946-bd069100-ba7b-11eb-9501-51958e1b7a08.png)

**Versioning:**
 - OS: Windows 10
 - NPM Version v7.14.0
- Module Version v7.1.4

**Additional Comments**
None.

**Comment by SushiBtw** [comment]
Thanks for the report, sorry for taking so much time - I am looking and resolving this issue now.

**Comment by SushiBtw** [comment]
Hey @CeaserPlayz, can you check now? It seems to be fixed on my side :)
