### ISSUE TITLE
[FR] Parallelism using worker threads

### ISSUE THREAD

**Issue by SpeckyYT** [SushiBtw/discord-music-player#137]
**Is your feature request related to a problem? Please describe.**
Sync code brickes/lags the music temporarily

**Describe the solution you'd like**
The only solution for this, is to use worker threads (AKA parallelism).
Cons: every function which communicates with the worker thread of music, has to be async.

```js
new Player(
    client,
    {
        workerThreads: true,
    }
)
```

**Describe alternatives you've considered**
There's aren't any 😭

**Additional Comments**
Despacito

**Comment by SushiBtw** [comment]
Not for now, maybe later - closing for now.
