### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Scarner56** [SushiBtw/discord-music-player#138]
I'm getting the error when using the hello module. Why?

_(node:5684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isPlaying' of undefinedat Object.run (C:\Users\Administrator\Desktop\sjbot\komutlar\çal.js:14:26)at Client.<anonymous> (C:\Users\Administrator\Desktop\sjbot\index.js:43:40)at Client.emit (events.js:327:22)at MessageCreateAction.handle (C:\Users\Administrator\Desktop\sjbot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Administrator\Desktop\sjbot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)at WebSocketManager.handlePacket (C:\Users\Administrator\Desktop\sjbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)at WebSocketShard.onPacket (C:\Users\Administrator\Desktop\sjbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)at WebSocketShard.onMessage (C:\Users\Administrator\Desktop\sjbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)at WebSocket.onMessage (C:\Users\Administrator\Desktop\sjbot\node_modules\ws\lib\event-target.js:132:16)at WebSocket.emit (events.js:315:20)(Use `node --trace-warnings ...` to show where the warning was created)(node:5684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. Thiserror originated either by throwing inside of an async function without a catchblock, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:5684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate theNode.js process with a non-zero exit code.

**Comment by SpeckyYT** [comment]
1) code?
2) that means that your "player" property is undefined / you didn't set it up.

**Comment by Scarner56** [comment]
module.exports = {
    code: "play",
    async run(client, message, args) {
        
        if(client.player.isPlaying(message)) {
            let song = await client.player.addToQueue(message, args.join(' '));

            // If there were no errors the Player#songAdd event will fire and the song will not be null.
            if(song)
                console.log(`Added ${song.name} to the queue`);
            return;
        } else {
            let song = await client.player.play(message, args.join(' '));

            // If there were no errors the Player#songAdd event will fire and the song will not be null.
            if(song)
                console.log(`Started playing ${song.name}`);
            return;
        }
    }
}

**Comment by SpeckyYT** [comment]
Where did you declare the player in `client.player`?

**Comment by SpeckyYT** [comment]
> I'm getting the error when using the hello module. Why?

The `hello` module?

**Comment by Scarner56** [comment]
I wrote it wrong it will be discord-music-player
now I'm defining and trying

**Comment by Scarner56** [comment]
problem solved thanks for your help :)

**Comment by Scarner56** [comment]
now the bot doesn't play music 



`module.exports = {
    code: "play",
    async run(client, message, args) {
        
        const { Player } = require("discord-music-player");
const player = new Player(client, {
  leaveOnEnd: false,
  leaveOnStop: false,
  leaveOnEmpty: true,
  timeout: 0,
  volume: 150,
  quality: 'high',
});
        client.player = player;
        if(client.player.isPlaying(message)) {
            let song = await client.player.addToQueue(message, args.join(' '));

            // If there were no errors the Player#songAdd event will fire and the song will not be null.
            if(song)
                console.log(`Added ${song.name} to the queue`);
            return;
        } else {
            let song = await client.player.play(message, args.join(' '));

            // If there were no errors the Player#songAdd event will fire and the song will not be null.
            if(song)
                console.log(`Started playing ${song.name}`);
            return;
        }
    }
}`

**Comment by Scarner56** [comment]
does not enter the voice channel and writes this to the console => Started playing undefined

**Comment by Scarner56** [comment]
please help

**Comment by Scarner56** [comment]
:(((

**Comment by Scarner56** [comment]
will nobody help :(

**Comment by Scarner56** [comment]
I wanted to use your module but can't use it because you didn't help so see you ...
