### ISSUE TITLE
[BUG]  error TS1005: ',' expected.

### ISSUE THREAD

**Issue by greysilly7** [SushiBtw/discord-music-player#143]
**Bug Description**
ITs late and I am tired so it errors when I compile with yarn and typescript 

**Reproduction Steps**
1. ``yarn init``
2. ``arn add discord-music-player@github:SushiBtw/discord-music-player``.
3. ``yarn tsc --build``

**Expected Result**
for it to compile without giving me a headache

**Attachments**

**Versioning:**
 - OS: Ubuntu 20.10
 - Yarn Version Berry
- Module Version latest on github I think
**Additional Comments**
error is
```
../../home/grey/.yarn/berry/cache/discord-music-player-https-07ea3e1ede-7.zip/node_modules/discord-music-player/typings/index.d.ts:7:27 - error TS1005: ',' expected.

7     channelEmpty: [message: Message, queue: Queue];
```

**Comment by SushiBtw** [comment]
I will look into the typings
