### ISSUE TITLE
Increase bitrate

### ISSUE THREAD

**Issue by MeshTheDev** [SushiBtw/discord-music-player#149]
Any way to increase bitrate?

**Comment by SpeckyYT** [comment]
`quality: 'high'` `quality: 'low'`

**Comment by MeshTheDev** [comment]
as in, is there a set value to it?

**Comment by MeshTheDev** [comment]
One more thing, you should update the installation section where it says "
Node.js 12.0.0 or newer is required to run this module.". Should be 14.0.0 and up since there would be errors when running the bot

**Comment by SpeckyYT** [comment]
What kind of errors

**Comment by SushiBtw** [comment]
> One more thing, you should update the installation section where it says "
> Node.js 12.0.0 or newer is required to run this module.". Should be 14.0.0 and up since there would be errors when running the bot

We are moving to nodev14 now.

**Comment by MeshTheDev** [comment]
> as in, is there a set value to it?

Noted. And for this?

**Comment by SushiBtw** [comment]
Only low/high, but I can look into improving it

**Comment by MeshTheDev** [comment]
Alright. Love the work you're doing here, easy to understand and helped me a lot!

**Comment by SushiBtw** [comment]
https://github.com/SushiBtw/discord-music-player#player-options
