### ISSUE TITLE
Bot won't play music

### ISSUE THREAD

**Issue by Thisisnotharry** [SushiBtw/discord-music-player#15]
Ok, so it joins the VC and it has the green ring around its pfp indicating it's talking, but nobody can hear anything?
I'm using the latest version, here's my code below:

_There are no errors in the console at all._

**index.js:**

const Discord = require('discord.js');
const client = new Discord.Client();
const fs = require('fs');
const newrelic = require('newrelic');
const request = require('request-promise')
const rateLimit = require("express-rate-limit");
const { Player } = require("discord-music-player");
const opuscript = require('@discordjs/opus')
const ytdl = require('ytdl-core')

const token = process.env.TOKEN;
const prefix = process.env.PREFIX;
const clientToken = process.env.YTTOKEN;
const server = require("./server.js");

const player = new Player(client);

client.player = player;

**play.js:**

const Discord = require('discord.js')

module.exports = {
	name: 'play',
	async run (client, message, args) {

let isPlaing = client.player.isPlaying(message.guild.id);

if(isPlaing){
            let song = await client.player.addToQueue(message.guild.id, args.slice(0).join(" "));
            song = song.song;
            message.channel.send(`${song.name} added to queue!`);
        } else {
            // Else, play the song
            let song = await client.player.play(message.member.voice.channel, args.slice(0).join(" "));
            song = song.song;
            message.channel.send(`Currently playing ${song.name}!`);
        }

  },
}

**Comment by Thisisnotharry** [comment]
Ok, I made another bot with the same code and packages, and it works, but the audio cuts out every 5-10 seconds, which is really annoying.

**Comment by SushiBtw** [comment]
Hello, is the bot internet connection good?

We are working on v6.0.0 (#14) update to fix the performance issues.

**Comment by Thisisnotharry** [comment]
The bot's internet connection is good, as it always has been.

**Comment by SushiBtw** [comment]
**This issue was resolved in [v6.0.0 Update](https://www.npmjs.com/package/discord-music-player/v/6.0.0).**

Thank you for reporting it.

**Comment by Thisisnotharry** [comment]
Yep, it sure is resolved!
