### ISSUE TITLE
[FR]  Song thumbnail info

### ISSUE THREAD

**Issue by Scarner56** [SushiBtw/discord-music-player#151]
**Is your feature request related to a problem? Please describe.**
I wanted to see the thumbnail of the music while the music is playing

**Describe the solution you'd like**
when the song starts playing, a thumbnail information about the song should be obtained

**Comment by SpeckyYT** [comment]
`Song.thumbnail` gives the URL to the thumbnail.

**Comment by Scarner56** [comment]
I didn't know that thanks
