### ISSUE TITLE
[BUG] When try play song it Returns 404

### ISSUE THREAD

**Issue by ChisdealHDYT** [SushiBtw/discord-music-player#155]
**Bug Description**
when try Run command for play song, it Returns Status: 404 as classify (404 Not Found)

**Reproduction Steps**
1. Use ``paimon!p`` command with ``skrillex`` options.
2. Tried update modules
3. Restart VPS
4. Check FFMPEG Installed that 100% is Installed

**Expected Result**
[17:49] ✔CUTIE ChisdealHDYT: paimon!p skrillex
[17:49] BOT PaimonBOT: SKRILLEX - Bangarang feat. Sirah [Official Music Video] has been added to the queue!
[17:49] BOT PaimonBOT: SKRILLEX - Bangarang feat. Sirah [Official Music Video] is now playing!
[17:49] BOT PaimonBOT: Unknown Error Ocurred: Status code: 404
[17:49] BOT PaimonBOT: Left Channel

**Versioning:**
 - OS: Ubuntu 20.04
 - NPM Version v7.16.0
- Module Version v7.1.4

**Additional Comments**
Was working before, this resent just start happening Today when this posted now?

no Error Logs ether, all says tried play and it forces not to.

**Comment by SushiBtw** [comment]
That's a age restricted video, it was fixed per [YTDL](https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6) but was not yet published per npm. As soon it will get on, I will update the package.

**Comment by SushiBtw** [comment]
This issue was fixed in [v7.2.0](https://www.npmjs.com/package/discord-music-player/v/7.2.0) update that is live on NPM. Tell me if the issue was fixed 🎉

**Comment by ChisdealHDYT** [comment]
ok gimmi sec test it out?

**Comment by ChisdealHDYT** [comment]
yep its fixed now, all working as normal.

**Comment by SushiBtw** [comment]
Thank you for the update, let me know if there will be any new issues as I changed the logic a bit.

Thanks again for using DMP and have a good day!
