### ISSUE TITLE
OptionsTypeInvalid error

### ISSUE THREAD

**Issue by CeaserPlayz** [SushiBtw/discord-music-player#16]
I just updated my library to the latest version (v6.0.1) and when I use my play command it gives me this error.
`MusicPlayerError {
  error: {
    type: 'OptionsTypeInvalid',
    message: 'The Search Options must be a type of Object.'
  },
  song: null
}`

This is my code: 
`const Discord = require("discord.js");
const Modules = require("../models/Modules");
const { music } = require("../colours.json");

module.exports = {
	name: 'play',
	description: 'Plays music.',
	aliases: ['p'],
	cooldown: 5,
	async execute(client, message, args, reason) {
        const embed = new Discord.MessageEmbed();
        const songname = args.toString().replace(",", " ")
        const module = await Modules.findOne({ where: { guildId: message.guild.id }})
        const musicmodule = module.getDataValue('music')

        console.log(songname)

        if(musicmodule === "false") return message.channel.send("The music module is not enabled. Use the `enable` command to activate it.")

        if(!message.member.voice.channel) return message.channel.send("You must join a voice channel first!");

        let isPlaying = client.player.isPlaying(message.guild.id);

        if(isPlaying){
            let song = await client.player.addToQueue(message.guild.id, songname, message.author.tag);
            song = song.song;
            embed.setDescription(`[${song.name}](${song.url}) has been added to the queue`);
            embed.setThumbnail(song.thumbnail);
            embed.setColor(music)
            message.channel.send(embed);
            
        } else {
            let song = await client.player.play(message.member.voice.channel, songname, message.author.tag);
            song = song.song;
            embed.setDescription(`Now playing [${song.name}](${song.url})`);
            embed.setThumbnail(song.thumbnail);
            embed.setColor(music);
            message.channel.send(embed);
            song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
                embed.setDescription(`Now playing [${newSong.name}](${newSong.url})`);
                embed.setThumbnail(newSong.thumbnail);
                message.channel.send(embed);
            });
        }
	},
};`

I'm not sure if it is just me or if other people are also getting this error.

**Comment by SushiBtw** [comment]
Just pass ``await client.player.addToQueue(message.guild.id, songname, {}, message.author.tag);``

and

``await client.player.play(message.guild.id, songname, {}, message.author.tag);``

**Comment by CeaserPlayz** [comment]
Thank you! That has fixed the issue for me.
