### ISSUE TITLE
What counts as a "queue"?

### ISSUE THREAD

**Issue by MeshTheDev** [SushiBtw/discord-music-player#162]
When i am playing a song and i loop it, i recieve an error telling me that the queue is null.

**Comment by SushiBtw** [comment]
Can you send me the code you are using? Be sure to not declare the Player on each command.

**Comment by MeshTheDev** [comment]
client.player.play(message, 'https://www.youtube.com/watch?v=t8EMx7Y16Vo')
    client.player.toggleLoop(message)

**Comment by MeshTheDev** [comment]
i made it such that it would play one song only, and then loop that song, but when it comes to the toggleloop command it returns the error but still plays the song

**Comment by SpeckyYT** [comment]
`.play` is async, be sure to await it, so the queue can get generated before toggling the queue.

**Comment by MeshTheDev** [comment]
also, which part of the 'message' object are you using in the play function?

i.e. .play( **message** , options)

**Comment by SpeckyYT** [comment]
Usually `<Message>.guild.id` and `<Message>.member.voice` get used

**Comment by MeshTheDev** [comment]
aight

**Comment by SushiBtw** [comment]
And `<Message>.channel` :)
