### ISSUE TITLE
[FR] Merge 2 functions

### ISSUE THREAD

**Issue by ItsYourBoyNoah** [SushiBtw/discord-music-player#164]
I was wondering, if it is possible to merge `<client>.player.playlist()` with `<client>.player.play()`. What I mean is when doing `client.player.play(message, "[my track])` it would support playlists too instead of having to use a whole new function.

**Comment by SushiBtw** [comment]
You can chrck if the provided link is a playlist link, then go on else, just use the play method.

I won't be merging them for now.
