### ISSUE TITLE
[BUG] Bot crashes without error message after playing a song

### ISSUE THREAD

**Issue by 4Lajf** [SushiBtw/discord-music-player#167]
**Bug Description**
Bot crashes without error message after playing a song. I tried playing a song with my bot and with example code which is in documentation and neither of it worked.

**Reproduction Steps**
1. Type !play <some song>

**Expected Result**
The bot plays the song.

**Attachments**
Here's console logs from the example code (they are the same on my bot so it dosen't really matter)
```
D:\path\to\file\index.js:235
                message.channel.send(exampleEmbed);
                                ^

TypeError: Cannot read property 'send' of undefined
    at Player.<anonymous> (D:\path\to\file\index.js:235:33)
    at Player.emit (node:events:369:20)
    at PassThrough.<anonymous> (D:\path\to\file\node_modules\discord-music-player\src\Player.js:740:24)
    at PassThrough.emit (node:events:381:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
and with console.log instead of message.channel.send as in `something went wrong ${error}`
`something went wrong $p castle of glass`
Here's the full bot code
https://wtools.io/paste-code/b5DO

**Versioning:**
 - OS: Windows 10 20H2
 - NPM Version npm@7.10.0
node@v15.14.0
- Module Version discord-music-player@7.2.0

**Comment by SushiBtw** [comment]
That's more like a issue with your code, we don't handle send messages on our side.
