### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [SushiBtw/discord-music-player#169]
![Screenshot_20210707-140536_Samsung Internet.jpg](https://user-images.githubusercontent.com/75924613/124729769-5c99b900-df2e-11eb-827f-90aef8a88b05.jpg)

**Comment by SushiBtw** [comment]
Node v14 is now LTS per https://nodejs.org/en/ and we will be moving for it in the newest 7.2.0 Update.

Please update your NodeJS version (#123).

**Comment by Xx-Mohit-xX** [comment]
Oky tysm
