### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Thisisnotharry** [SushiBtw/discord-music-player#17]
When looping something, rather than having 2 separate commands, could you make it so it checks to see if the song is looped, so then you could do !loop and it automatically loop / unloop?

Also, for the queue command, can you add something that would make it say who requested the song, rather than just a list of songs?

**Comment by SushiBtw** [comment]
Hey, ``setRepeatMode(GuildID, boolean)`` will be deprecated in the newest updates, and there will be a ``toggleLoop(guildID)`` function instead.

You can pass in the ``play`` and ``addToQueue`` the **RequestedBy** option:
```js
client.player.play(VoiceChannel, SongName, Options, RequestedBy);
client.player.addToQueue(SongName, Options, RequestedBy);
```

**Comment by Thisisnotharry** [comment]
> Hey, `setRepeatMode(GuildID, boolean)` will be deprecated in the newest updates, and there will be a `toggleLoop(guildID)` function instead.
> 
> You can pass in the `play` and `addToQueue` the **RequestedBy** option:
> 
> ```js
> client.player.play(VoiceChannel, SongName, Options, RequestedBy);
> client.player.addToQueue(SongName, Options, RequestedBy);
> ```

What "Options" are there in client.player.play(VoiceChannel, SongName, Options, RequestedBy); ?

**Comment by Aduzy** [comment]
You can find all available Options in [Documentation](https://github.com/SushiBtw/discord-music-player#documentation)


(Sorry Sushi)

**Comment by Thisisnotharry** [comment]
Ah, okay, thanks!

**Comment by SushiBtw** [comment]
As @Aduzy said, everything is there.
(Thanks and your welcome).

**Comment by SushiBtw** [comment]
Closing due inactivity.
