### ISSUE TITLE
[BUG] SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by iiAlanii** [SushiBtw/discord-music-player#170]
/home/runner/NuL/node_modules/discord-music-player/src/Player.js:56
        return this.queues.has(message?.guild?.id);
                                       ^

SyntaxError: Unexpected token '.'
![Screenshot 2021-07-07 133313](https://user-images.githubusercontent.com/85262775/124752311-ff026e00-df27-11eb-9b1e-00f373fde75c.gif)

**Comment by SpeckyYT** [comment]
Node v14 is now LTS per https://nodejs.org/en/ and we will be moving for it in the newest 7.2.0 Update.

**Comment by SpeckyYT** [comment]
(I guess this can get closed)
