### ISSUE TITLE
[BUG] 404 error when playing a song

### ISSUE THREAD

**Issue by 4Lajf** [SushiBtw/discord-music-player#171]
**Bug Description**
404 error when playing a song

**Reproduction Steps**
1. Try to play a song
2. 404 error happens

**Expected Result**
song should play

**Attachments**
```
Playing YOASOBI "Racing into the Night"  Official Music Video //song that i tried to play
//error code
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 404')
    at new NodeError (node:internal/errors:329:5)
    at Player.emit (node:events:358:17)
    at PassThrough.<anonymous> (/var/bot/node_modules/discord-music-player/src/Player.js:705:24)
    at PassThrough.emit (node:events:381:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Status code: 404'
}
```

**Versioning:**
 - OS: Arch Linux 5.11.11 as well as Windows 10 - 20H2
 - NPM Version 7.10.0
- Module Version 7.2.0

The exact code the bot is running https://ghostbin.com/paste/2wnx2 (it's copy paste from docs anyway)
I also tried to reinstall it multiple times. Rebooting machine and so on.

**Comment by SushiBtw** [comment]
That issue was fixed in v8 - #177
