### ISSUE TITLE
[BUG] Songs not playing before queue end.

### ISSUE THREAD

**Issue by 442predator442** [SushiBtw/discord-music-player#174]
**Bug Description**
When queue end when adding a new song, it is not played. Also, the last played song remains in the playlist.

**Reproduction Steps**
1. Play songs (add songs to playlist with command 'play').
2. Songs lost, queue end.
3. Add new song (with command 'play')
4. The last played song remains in the playlist and songs are not played.

**Expected Result**
Playlist have 1 new song in playlist after queue is end and song is played.

**Attachments**
Screenshots attached

**Versioning:**
 - OS: [Hosting: Linux]
 - NPM Version [v14.17.0]
- Module Version [v7.2.0]

**Additional Comments**
Command 'play' in code
![playCommand](https://user-images.githubusercontent.com/58422307/127563817-2f2de48e-574f-49c1-b1bf-c988162d0118.png)
Songs not added (playlist is empty)
P.S.: bot has mark 'talking'
![playListNotStarted](https://user-images.githubusercontent.com/58422307/127563767-c8a14777-f2ab-4064-b91a-9879eed7b8e2.png)
Add song to empty playlist
P.S.: bot has mark 'talking'
![botIsPlaying](https://user-images.githubusercontent.com/58422307/127563868-d0d0cea0-fd43-4116-bb29-84f4686ccbbb.png)
Song is end and queue is end.
P.S.: bot is not have mark 'talking'
![queueEnd](https://user-images.githubusercontent.com/58422307/127563898-33197ee5-5741-4c8f-8b09-5188b8194541.png)
Add new song and we see that there are 2 songs in the playlist.
![addSongAfterQueueEnd](https://user-images.githubusercontent.com/58422307/127563957-0bee6f20-5546-46d3-9a56-eefca5840fb0.png)
Try to skip the song
P.S.: song is not skipped (outside the bug, this command is works)
![tryToSkip](https://user-images.githubusercontent.com/58422307/127564828-067dbe1b-f146-4fb0-a65e-467b7208bdeb.png)

**Comment by SushiBtw** [comment]
Fixed in v8 - #177
