### ISSUE TITLE
[BUG] `InvalidPlaylist` when its Valid URL

### ISSUE THREAD

**Issue by ChisdealHDYT** [SushiBtw/discord-music-player#176]
Tried `%!pl https://youtu.be/playlist?list=PLSBwjXG1S2xSRMhIPYS70d2cGWQYNGM0K` & `%!pl https://youtube.com/playlist?list=PLSBwjXG1S2xSRMhIPYS70d2cGWQYNGM0K`

it responding as Invalid Playlist, its on latest discord-music-player and i have confirmed this happen mine bot as well not just my friends too.

i dont know got Rework going round it, but at moment Playlist command not working anymore just only `Play command` works so far i have tested it

**Comment by SushiBtw** [comment]
Will try to adress that issue in v8 - #177

**Comment by SushiBtw** [comment]
Fixed in v8 [dev build] - Read more here - (#177).
