### ISSUE TITLE
[FR] Support for other than Discord.Message

### ISSUE THREAD

**Issue by mikkel-ol** [SushiBtw/discord-music-player#178]
Firstly, thank you for a great library.

At the moment all methods require a `Discord.Message` object to be passed to it. This effectively means that the music player can only be used when a message is received.

However I would like to be able to use it with an API layer, where no `Discord.Message` is present. Theoretically it should only be required to specify a voice channel to play music (and of course the song/search string).

Therefore I propose support for only channel ID and using the client to look up the rest (eg. Guild for the queue etc.) or some sort of custom object.

I hope it makes sense.

**Comment by SushiBtw** [comment]
Hey, you can now pass custom data in the `development` build (for Discord.JS v13).
Check how to use it https://github.com/SushiBtw/discord-music-player/tree/development#passing-custom-data.

Also, changes in v8@dev - #177

**Comment by mikkel-ol** [comment]
That is exactly what I needed. Thank you very much :)
