### ISSUE TITLE
Create a Discord server for support.

### ISSUE THREAD

**Issue by TechPro424** [SushiBtw/discord-music-player#181]
**Is your feature request related to a problem? Please describe.**
For a Discord.js module, it would be easier to ask for support if we have a Discord server or similar.

**Describe the solution you'd like**
Create a Discord server.

**Additional Comments**
While I'm making this issue, I want to ask 2 more questions:

1) Can I set the music volume separately for each guild? If yes, how?
2) Can I play different songs in different voice channels using this module? If yes, how?

**Comment by SpeckyYT** [comment]
https://ssumbot.xyz/discord
