### ISSUE TITLE
[BUG] Volume not correct

### ISSUE THREAD

**Issue by mikkel-ol** [SushiBtw/discord-music-player#188]
**Bug Description**
`queue.volume` is not returning expected value.

**Reproduction Steps**
1. Set volume to 50
2. Get volume, will return 25

**Expected Result**
Expecting volume to return same value as set

**Versioning:**
- OS: Windows 10
- NPM Version: 7.21.0
- Module Version 8.0.1

**Comment by SushiBtw** [comment]
Hey, thanks for the report. I can reproduce this issue and it was already reported on our discord, but thanks for the report.

I will fix this asap, and let you know.

**Comment by SushiBtw** [comment]
Hey, that issue was fixed in [DMP v8.0.2](https://www.npmjs.com/package/discord-music-player/v/8.0.2).
```sh
npm i discord-music-player@8.0.2
```

Thanks @mikkel-ol and @SpeckyYT for reporting it.
