### ISSUE TITLE
[BUG] youtube videos with disabled comment sections are unplayable

### ISSUE THREAD

**Issue by Vap0r1ze** [SushiBtw/discord-music-player#189]
i dont think regular youtube links [get detected by your regex](https://github.com/SushiBtw/discord-music-player/blob/16982b5c2c64fd0f333906236cdec93929beda43/src/utils/Utils.ts#L20)

like `https://www.youtube.com/watch?v=-LgYzva-xq8`

**Comment by Vap0r1ze** [comment]
they do im just tired and assumed the issue, ignore this

**Comment by Vap0r1ze** [comment]
the issue ended up being SuspiciousLookingOwl/youtubei#25 if you're curious

**Comment by SushiBtw** [comment]
Will let you know when that is fixed.

**Comment by SushiBtw** [comment]
Fixing this issue in few moments.

**Comment by SushiBtw** [comment]
Fixed in [v8.1.0](https://www.npmjs.com/package/discord-music-player/v/8.1.0).
```sh
npm i discord-music-player@8.1.0
```
