### ISSUE TITLE
Wrong properties on links

### ISSUE THREAD

**Issue by SpeckyYT** [SushiBtw/discord-music-player#19]
check the images, it should be enough to understand what's about

[search by name](https://cdn.discordapp.com/attachments/704978437911347260/783449972703625256/unknown.png)
[search by URL](https://cdn.discordapp.com/attachments/704978437911347260/783450120116109322/unknown.png)

**Comment by SushiBtw** [comment]
I am going to work on a update per it.

**Comment by SushiBtw** [comment]
I started working on it, the update will there in 48 hours.

**Comment by SushiBtw** [comment]
Hello, this issue was fixed in [v.6.2.0 Update](https://github.com/SushiBtw/discord-music-player/commit/8973ffa932e18b9da590f44658b7d3a182467efc) - please check and reopen the issue if needed.

NPM link: https://www.npmjs.com/package/discord-music-player/v/6.2.0
