### ISSUE TITLE
[BUG] Short bug description

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#190]
**Bug Description**
The bot starts fine but when I run the >play command I get a error (see screen shot)

**Expected Result**
the >play command is meant to play music

**Attachments**
see screen shot for error
![Screenshot (35)](https://user-images.githubusercontent.com/68092869/133059401-46db3eb7-9a73-483b-b98d-50a0f37164c0.png)

**Comment by SpeckyYT** [comment]
Could you provide any code?

**Comment by SushiBtw** [comment]
Are you using Discord.js v13?

**Comment by EclipseGame18** [comment]
this is my play command:
} else if (command == 'play') {
        let queue = client.player.createQueue(message.guild.id);
        await queue.join(message.member.voice.channel);
		const playEmbed = new Discord.MessageEmbed()
				.setTitle("Now Playing:")
		                .addField(`Now playing:`, `${song.name}`)
		                .addField(`Requested by:`, `${song.requestedBy}`)
				.setColor('#6CFFD9');
			message.channel.send(playEmbed);
        let song = await queue.play(args.join(' ')).catch(_ => {
            if(!guildQueue)
                queue.stop();
        });

**Comment by EclipseGame18** [comment]
also discord.js is 12.5.3

**Comment by SushiBtw** [comment]
This module is v13 only.
