### ISSUE TITLE
[BUG] Official Vevo Youtube Links throw an error

### ISSUE THREAD

**Issue by LyrasaurusRose** [SushiBtw/discord-music-player#192]
**Bug Description**
When trying to stream songs, songs that are official vevo links (ex: https://www.youtube.com/watch?v=pDFCCBxNX7c and https://www.youtube.com/watch?v=QYh6mYIJG2Y) the bot will throw 
`TypeError: Cannot read property 'contents' of undefined: There was an Unknown Error.
    at \node_modules\discord-music-player\dist\managers\Queue.js:185:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Reproduction Steps**
1. Use ``play`` command with any "vevo" official release music link. (some examples linked above, but it is consistent on every vevo track I've tried.)
2. The play function I use is the following, in case it is relevant for debug purposes: `let song = await queue.play(query).catch((err) => {
        console.log(err);
        if (!queue) queue.stop();
      });`
2. Upon attempting to play the song, the bot will throw the error in the console, and my error handler message is sent to my discord channel.

**Expected Result**
The song to play and not error, all other songs seem to work.

**Attachments**

**Versioning:**
- OS: Windows 10
- Node Version v16.8.0
- Module Version v8.0.2

**Additional Comments**
I posted this in the Discord server but wanted to make an official issue just to keep things organized.

**Comment by SushiBtw** [comment]
Hey, thanks for letting me know. I will be looking into it today, and hotfix this issue.

**Comment by DiegoDelgado95** [comment]
Hi, i had the same problem, and it is a problem from the 'youtubei' library! the version '0.0.1-rc.20' has a bug with the videos that have purchase sections, u need to update to version "0.0.1-rc.24"

**Comment by SushiBtw** [comment]
I will be updating all the dependencies today. Thanks for letting me know.

**Comment by LyrasaurusRose** [comment]
Can confirm that using `npm i youtubei@latest` to update to '0.0.1-rc.24' fixes the issue.

**Comment by SushiBtw** [comment]
Fixed in [v8.1.0](https://www.npmjs.com/package/discord-music-player/v/8.1.0).
```sh
npm i discord-music-player@8.1.0
```
