### ISSUE TITLE
[FR] Allow us to pass in cookies to YTDL

### ISSUE THREAD

**Issue by LyrasaurusRose** [SushiBtw/discord-music-player#193]
**Is your feature request related to a problem? Please describe.**
In order to allow the downloading and streaming of Age Restricted songs, YTDL requires a user cookie. Other libraries allow the programmer to pass this user cookie into the player which passes it for use to YTDL.

**Describe the solution you'd like**
Create a player option that will accept a user cookie, and pass it to YTDL.

**Additional Comments**
I posted this FR in the discord but wanted to make an issue here to keep things organized :)

**Comment by SushiBtw** [comment]
Added support for ytdlCookies in [v8.1.0](https://www.npmjs.com/package/discord-music-player/v/8.1.0).

Check https://discord-music-player.js.org/docs/main/master/typedef/PlayerOptions
