### ISSUE TITLE
How to add song name in chat channel

### ISSUE THREAD

**Issue by kurumicute** [SushiBtw/discord-music-player#197]
Versioning:

OS: Windows 10
Node Version: v16.6.1
Module Version: v8.0.2

i just want to add song name in chat channel but i cant

**Comment by SpeckyYT** [comment]
"add song name in chat channel" sounds quite vague

**Comment by kurumicute** [comment]
like 
![image](https://user-images.githubusercontent.com/90886946/133925462-aab12da3-95fd-4ec0-bbf4-5540ef5f9ee0.png)
but in words

**Comment by kurumicute** [comment]
> "add song name in chat channel" sounds quite vague

ike
![image](https://user-images.githubusercontent.com/90886946/133925533-bf35ce52-4da6-4801-9aa1-1141db68ed48.png)

but in words

**Comment by SpeckyYT** [comment]
when you `<Queue>.play()`, it returns a promise which results into a `song`, you can use it for whatever you want.
and also, have fun getting banned by discord for using an unofficial client.

**Comment by kurumicute** [comment]
> when you `<Queue>.play()`, it returns a promise which results into a `song`, you can use it for whatever you want.
> and also, have fun getting banned by discord for using an unofficial client.

This is my friend's computer, not mine
I told him before but he didn't listen

Can you give me an example?  i'm a noob :P

**Comment by SpeckyYT** [comment]
start off with
```js
const queue = bot.player.getQueue(msg.channel.id);
const song = await queue.play("despacito");
console.log(song)
```
and the rest should be obvious.

**Comment by kurumicute** [comment]
> start off with
> 
> ```js
> const queue = bot.player.createQueue(msg.channel.id);
> const song = await queue.play("despacito");
> console.log(song)
> ```
> 
> and the rest should be obvious.

```
client.on('messageCreate', async (message) => {
    console.log(song)
    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift();
    const song = await queue.play("despacito");
    const queue = client.player.createQueue(message.channel.id);
    let guildQueue = client.player.getQueue(message.guild.id);

    if(command === 'play') {
        let queue = client.player.createQueue(message.guild.id);
        await queue.join(message.member.voice.channel);
        let song = await queue.play(args.join('')).catch(_ => {
            if(!guildQueue)
                queue.stop();
        });
    }
```

sorry i can't...
I used js for the first time

**Comment by SpeckyYT** [comment]
you seriously declared the queue after the song?

**Comment by kurumicute** [comment]
> you seriously declared the queue after the song?

I really don't know how to use js
sorry...

**Comment by kurumicute** [comment]
> you seriously declared the queue after the song?


Can you tell me what to do next?...

**Comment by SpeckyYT** [comment]
> > you seriously declared the queue after the song?
> 
> Can you tell me what to do next?...

1) learn JS
2) put `const song = ...........` after `const queue = ...........`
3) https://tryitands.ee

**Comment by SushiBtw** [comment]
Closing, offtopic.
