### ISSUE TITLE
getQueue is returning an empty array and isPlaying returning false even though it is playing music

### ISSUE THREAD

**Issue by CeaserPlayz** [SushiBtw/discord-music-player#2]
This is my play command right now:
`const Discord = require("discord.js");

module.exports = {
	name: 'play',
	description: 'Plays music.',
	aliases: ['p'],
	cooldown: 5,
	async execute(client, message, args, reason, player) {
        const embed = new Discord.MessageEmbed();
        const songname = args.toString();
        
        client.player = player;

        if(!message.member.voice.channel) return message.channel.send("You must join a voice channel first!");

        let isPlaying = client.player.isPlaying(message.guild.id);

        if(isPlaying){
            let song = await client.player.addToQueue(message.guild.id, songname);
            song = song.song;
            embed.setDescription(`[${song.name}](${song.url}) has been added to the queue`);
            embed.setThumbnail(song.thumbnail)
            message.channel.send(embed);
            
        } else {
            let song = await client.player.play(message.member.voice.channel, songname).catch(err => message.channel.send("I could not play that song."));
            song = song.song;
            embed.setDescription(`Now playing [${song.name}](${song.url})`);
            embed.setThumbnail(song.thumbnail);
            message.channel.send(embed);
            console.log(isPlaying)
            song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
                embed.setDescription(`Now playing [${newSong.name}](${newSong.url})`);
                embed.setThumbnail(newSong.thumbnail);
                message.channel.send(embed);
            });
        }
	},
};`

When I use the play command, it will play the first song, but when I add a song to the queue, it will just instantly play the new song. Also when I console log .getQueue it returns as an empty array. Did I do something wrong for this to happen?

Note: Github codeblock isn't working how I wanted it to work so ignore the `'s at the start and the end of the code

**Comment by SushiBtw** [comment]
Hello @CeaserPlayz, can you please tell me why are you defining `client.player` as `player` (can you please avoid it) - the client.player will update their self, there is no needed to define if every time.
Define it on the start (index) of your code and please remove `client.player = player` in the command, and let me know if it's still happening.

**Comment by CeaserPlayz** [comment]
I am using the guide from the npm website, and it said to define client.player as player. https://www.npmjs.com/package/discord-music-player . I also already have player defined in my message.js file (message event since I put a event handler in there) and then put it into the .execute part of the code.

**Comment by SushiBtw** [comment]
Can you please send you index code (where Player is defined) & the full command code? That will help us to look into the issue.

Here is a example working code:
```js
// Definition code (index.js)
const { Player } = require("discord-music-player");
const player = new Player(client);
client.player = player;

// Middle code (play.js)
let exampleSong = 'Test Song';
let isPlaying = client.player.isPlaying(message.guild.id);

    if(isPlaying){
      // Add Song to Queue
        client.player.addToQueue(message.guild.id, exampleSong).then(async callback => {
          if(callback.error) throw(callback.error);
          let song = callback.song;
          
          return message.channel.send(`**${song.name}** has been added to the queue!`);
          
        }).catch(async err => {
          
            return await message.channel.send(`No Song found with that query.`);
        });
      
    } else {
        // Start playing a Song
        client.player.play(message.member.voice.channel, exampleSong).then(async callback => {
            if(callback.error) throw(callback.error);
            let song = callback.song;
          
            message.channel.send(`Now Playing: **${song.name}**!`);
          
            song.queue.on('end', () => {
              message.channel.send(`The queue is empty, there is nothing to play.`);
            });

            song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
                if(repeatMode){
                    message.channel.send(`Repeating: **${oldSong.name}**`);
                } else {
                    message.channel.send(`Now Playing: **${newSong.name}**!`);
                }
            });
        }).catch(async err => {
            return await message.channel.send(`No Song found with that query.`);
        });
    }
```

Please let me know, if the code would work, if not, please try reinstalling the module:
```
npm uninstall
npm install discord-music-player
```
I am marking this issue as a Bug.

**Comment by CeaserPlayz** [comment]
My code where player is defined:
`const Discord = require("discord.js");
const Guilds = require("../models/Guilds");
const Modules = require("../models/Modules");
const { Player } = require("discord-music-player");
const cooldowns = new Discord.Collection();

module.exports = async (client, message) => {
    await Guilds.findOrCreate({ where: { guildId: message.guild.id }, defaults: { guildPrefix: "s!", radioOn: "false", repeatOn: "false" }});
    await Modules.findOrCreate({ where: { guildId: message.guild.id }, defaults: { music: "true", welcoming: "false", application: "false" }});
    let prefixes = await Guilds.findOne({ where: { guildId: message.guild.id }});
    let prefix = prefixes.getDataValue('guildPrefix');
    if (!message.content.startsWith(prefix) || message.author.bot) return;

	const args = message.content.slice(prefix.length).trim().split(/ +/);
    const commandName = args.shift().toLowerCase();
    const reason = args.slice(1);
    const player = new Player(client);
    

    const command = client.commands.get(commandName)
		|| client.commands.find(cmd => cmd.aliases && cmd.aliases.includes(commandName));

	if (!command) return;
    if (!cooldowns.has(command.name)) {
        cooldowns.set(command.name, new Discord.Collection());
    }
    
    const now = Date.now();
    const timestamps = cooldowns.get(command.name);
    const cooldownAmount = (command.cooldown || 3) * 1000;
    
    if (timestamps.has(message.author.id)) {
        if (timestamps.has(message.author.id)) {
            const expirationTime = timestamps.get(message.author.id) + cooldownAmount;
        
            if (now < expirationTime) {
                const timeLeft = (expirationTime - now) / 1000;
                return message.reply(`please wait ${timeLeft.toFixed(1)} more second(s) before reusing this command.`);
            }
        }
    }

    timestamps.set(message.author.id, now);
    setTimeout(() => timestamps.delete(message.author.id), cooldownAmount);

    try {
        command.execute(client, message, args, reason, player);
    } catch (error) {
        console.error(error);
        message.reply('there was an error trying to execute that command!');
    }
}`

Command code:
`const Discord = require("discord.js");

module.exports = {
	name: 'play',
	description: 'Plays music.',
	aliases: ['p'],
	cooldown: 5,
	async execute(client, message, args, reason, player) {
        const embed = new Discord.MessageEmbed();
        const songname = args.toString();

        if(!message.member.voice.channel) return message.channel.send("You must join a voice channel first!");

        let isPlaying = player.isPlaying(message.guild.id);

        if(isPlaying){
            let song = await player.addToQueue(message.guild.id, songname);
            song = song.song;
            embed.setDescription(`[${song.name}](${song.url}) has been added to the queue`);
            embed.setThumbnail(song.thumbnail)
            message.channel.send(embed);
            
        } else {
            let song = await player.play(message.member.voice.channel, songname).catch(err => message.channel.send("I could not play that song."));
            song = song.song;
            embed.setDescription(`Now playing [${song.name}](${song.url})`);
            embed.setThumbnail(song.thumbnail);
            message.channel.send(embed);
            console.log(isPlaying)
            song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
                embed.setDescription(`Now playing [${newSong.name}](${newSong.url})`);
                embed.setThumbnail(newSong.thumbnail);
                message.channel.send(embed);
            });
        }
	},
};`

I have already tried uninstalling the package and reinstalling it, but it still gives the same problem

**Comment by SushiBtw** [comment]
Okay, I see, that you define the Player on every message - **don't do it.**

Please define the Player under the `client` definition:
```
const client = new Discord.Client();
// Here define the Music Player
const player = new Player(client);
client.player = player;
```
*Remember to remove the Player definition from the onMessage event.*

Please update me, if it's working properly.

**Comment by CeaserPlayz** [comment]
I can't do that as if I replace "player" with "client.player" in the .execute section of the message event code and then replace "player" with "client.player", it will give me syntax errors. 
![image](https://user-images.githubusercontent.com/66173114/98450690-9e235b80-2136-11eb-97af-367ba7f4ee9e.png)

![image](https://user-images.githubusercontent.com/66173114/98450685-8d72e580-2136-11eb-9651-f7b1d714a270.png)

**Comment by SushiBtw** [comment]
Please define in your index file:
```js
// Here define the Music Player
const player = new Player(client);
client.player = player;
```
after `client.modules`.

Then in the execute file, leave player as it was.
*In onMessage remove the Player definition (you have **client.player**).*

From the play.js change client.player to player.

Read my latest message once again.

**Comment by CeaserPlayz** [comment]
I edited the command.execute section of my code to just `command.execute(client, message, args, reason)` and removed the player definition from it  I have added `client.player = player` and `const player = new Player(client)` in my index.js file. In my play.js file, I changed the async execute section to be `async execute(client, message, args, reason, player)` . But then, when I run my play command, it'll return "player is not defined"

**Comment by SushiBtw** [comment]
You have now defined `client.player`, so remove from `async execute(client, message, args, reason, player)` the player [so you have `async execute(client, message, args, reason)`].

Example:
```js
client.player.isPlaying(message.guild.id);
```

Update me, if it's working.

Now you can use `client.player`, not `player`.

**Comment by CeaserPlayz** [comment]
Ah, okay. It works now, thank you for your help. I apologise that you had to spoon feed me a little.
