### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VOTRON157** [SushiBtw/discord-music-player#20]
congratulations on your package and very good, I wanted to suggest to add the option to add complete playlist to the queue.

**Comment by SushiBtw** [comment]
Hey! Thanks for the feedback :)

Yeah, that's possible, thanks for it! It will be added soonly.

**Comment by SushiBtw** [comment]
Live on https://www.npmjs.com/package/discord-music-player/v/6.3.0.
