### ISSUE TITLE
[BUG] Bot playing a random song

### ISSUE THREAD

**Issue by xMiniLuke** [SushiBtw/discord-music-player#203]
**Bug Description**
Im currently making my own discord music bot by using this script, and when i put an YouTube URL on the  play command, suddenly a other song than that link is playing.

**Reproduction Steps**

 In the .js file i have following code:

"const Command = require("../Structures/Command.js");

module.exports = new Command({
    name: "p",
    description: "Play a song!",

    async run(message, args, client) {
        
        let queue = client.player.createQueue(message.guild.id);
        let guildQueue = client.player.getQueue(message.guild.id);
        await queue.join(message.member.voice.channel);
        let song = await queue.play(args.join(' ')).catch(_ => {
            if(!guildQueue)
                queue.stop();

                
        });

        message.reply(`Now playing: \`${guildQueue.nowPlaying}\` `);
        

    }
})"

**Additional Comments**
Im sorry if i did any wrong grammatics, im not that good in english, because my main-language is german.

**Comment by SushiBtw** [comment]
can you send me the log from `console.log(args.join(' '));`?

**Comment by xMiniLuke** [comment]
Where can i find that log? Im kinda new to JavaScript so i dont know where to find anything

**Comment by SushiBtw** [comment]
Just add `console.log(args.join(' '));` after your `async run(message, args, client) {` line.
It will log the args in the console.

**Comment by SushiBtw** [comment]
Can you show me your message.js command - as seems you have been passing the command arg too.

**Comment by SushiBtw** [comment]
Can you show me the index.js file with the `message/messageCreate` file?

**Comment by xMiniLuke** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/91219957/134407394-8080986c-553f-49a0-bf6b-4e193649658a.png)

Here you go

**Comment by SushiBtw** [comment]
Can you please add `args.shift()` before command.run?

**Comment by xMiniLuke** [comment]
Well, did it, ran it and it loadet the right video, but the bot instantly crashed:

https://www.youtube.com/watch?v=mBPa-EUxGyY
node:events:385
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 403')
    at new NodeError (node:internal/errors:371:5)
    at Player.emit (node:events:383:17)
    at FFmpeg.<anonymous> (C:\Users\minil\Desktop\MiniBot\node_modules\discord-music-player\dist\managers\Queue.js:228:33)
    at FFmpeg.emit (node:events:406:35)
    at PassThrough.<anonymous> (C:\Users\minil\Desktop\MiniBot\node_modules\discord-ytdl-core\index.js:1:1100)
    at PassThrough.emit (node:events:406:35)
    at PassThrough.emit (node:events:394:28)
    at ClientRequest.<anonymous> (C:\Users\minil\Desktop\MiniBot\node_modules\miniget\dist\index.js:215:28)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Status code: 403'
}

**Comment by SushiBtw** [comment]
Can you try again?

**Comment by xMiniLuke** [comment]
Works now, thanks for the help man!
