### ISSUE TITLE
Support for using custom extractors such as play-dl for yt

### ISSUE THREAD

**Issue by naseif** [SushiBtw/discord-music-player#204]
I have been using discord-player for a while now and I have been suffering from abort issues with yt-dl and some unknown bugs as well. I did some testing with play-dl and in comparison with yt-dl it's way better. I want to suggest giving the user the option of passing an object to the play method containing the info from the other extractor instead of being limited to only pass the result coming from Utils.search method to enable users using different extractors instead of being limited to the library's one.

**Comment by SushiBtw** [comment]
I will be looking into it.

**Comment by SushiBtw** [comment]
Won't be adding for now, but maybe with v9 or late v8, this feature will come up, as I would need to re-write a lot of code.
