### ISSUE TITLE
Spamming in channel

### ISSUE THREAD

**Issue by kabirsingh2004** [SushiBtw/discord-music-player#209]
When i Play song bot spam in channel like added to queue and Playing 
how to fix ?

**Comment by SushiBtw** [comment]
Remove the player events from discord events.

**Comment by kabirsingh2004** [comment]
also song not playing 
why

**Comment by EclipseGame18** [comment]
I have the same problem I put the events outside of the 'messageCreate' event but now I wont send the embeds
