### ISSUE TITLE
Youtube URL issue

### ISSUE THREAD

**Issue by OxYGxD** [SushiBtw/discord-music-player#21]
When I post the youtube url with the command in the chat, this message comes to the console, how can I solve this problem

[DMP] YouTube returned a empty object, you are probably rate-limited (please wait some time) - The Author and Title are Unknown.

Here is my code : http://codebin.herokuapp.com/?s=5fccc1784ebb3d0004000002

![issue1](https://user-images.githubusercontent.com/28568468/101278733-a373d480-37ce-11eb-8bef-6a549ad3a60f.PNG)

**Comment by SpeckyYT** [comment]
https://github.com/SushiBtw/discord-music-player/issues/19

**Comment by SushiBtw** [comment]
This is a new feature for ratelimits, but we are working to solve this.

**Comment by SushiBtw** [comment]
Hello, this issue was fixed in [v.6.2.0 Update](https://github.com/SushiBtw/discord-music-player/commit/8973ffa932e18b9da590f44658b7d3a182467efc) - please check and reopen the issue if needed.

NPM link: https://www.npmjs.com/package/discord-music-player/v/6.2.0
