### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#212]
Is there a way to get a list of songs with the current queue and then send it to a channel? because the old queue code does not work.

**Comment by SpeckyYT** [comment]
```js
const { songs } = player.getQueue(msg.guild.id);

console.log(songs);
```

**Comment by EclipseGame18** [comment]
ok thx

**Comment by EclipseGame18** [comment]
but how do i add a space after the ,

**Comment by SpeckyYT** [comment]
> but how do i add a space after the ,

there is no usage of `,` in the snippet I provided

**Comment by EclipseGame18** [comment]
when I send `songs`  in a message e.g. `message.channel.send('queue ${songs}')` it come out like
songname1,songname2,songname3 etc

**Comment by EclipseGame18** [comment]
thanks it works!

**Comment by SushiBtw** [comment]
Thanks for letting me know!
