### ISSUE TITLE
[FR] Move song in queue to a different position

### ISSUE THREAD

**Issue by MrJamesT** [SushiBtw/discord-music-player#213]
**Is your feature request related to a problem? Please describe.**
The last missing feature for me is the ability to `move` a song in the queue.

**Describe the solution you'd like**
A `move` command that would work like `move <trackIndex> <toIndex>` in the queue.

**Describe alternatives you've considered**
Perhaps directly modifying the queue array, but I'm not sure if that's advised.

**Comment by SpeckyYT** [comment]
```js
const songIndex = 5
const insertIndex = 2
const song = <Queue>.songs.splice(songIndex,1);
<Queue>.songs.splice(insertIndex,0,...song);
```

**Comment by SushiBtw** [comment]
Maybe I will add such a function, for now - use the code above.
