### ISSUE TITLE
[BUG] Track starts playing for 1 second, then skips to next song in queue

### ISSUE THREAD

**Issue by MrJamesT** [SushiBtw/discord-music-player#219]
**Bug Description**
In like 1/10 cases, a random track from the queue will get skipped after playing for about 1 second and no errors are logged, despite every command being in a trycatch statement.

**Reproduction Steps**
1. Put some tracks into the queue
2. Wait for a track which gets skipped

**Expected Result**
The track would be played whole or at least an error will show describing what happened.

**Attachments**
Not applicable, no errors logged.

**Versioning:**
- OS: Ubuntu 20.04, but it also happens when testing on my Windows 10 PC
- Node Version 16.9.1
- Module Version 8.1.0

**Additional Comments**
-

**Comment by hunter-hulk** [comment]
is it possible to get an example link or two. i can run a few tests and see what i get. sounds like its probably a ytdl problem could just be that ytdl is still rc and not necessarily stable.

**Comment by LyrasaurusRose** [comment]
It actually seems like it could very possibly be a DMP error, as when I change out the ytdl for play-dl (was playing with things) it still happens, but on a simple test bot I have where I wrote a script to just play a song using play-dl it works fine. ytdl can also grab the song fine and convert it into a video file using ffmpeg, so I'm not entirely sure what the problem could be as we're not getting any error messages or anything from DMP to help figure that out.

**Comment by hunter-hulk** [comment]
i also just checked the duration of the video out from ytdl and it was correct so it much be a queue problem or DMP error as you said.

**Comment by hunter-hulk** [comment]
just tried that and running it about 30 times seems to fix it about 5 out of 6 times but still getting a fail which is not good. without that it seems to fail about 3 out of 4 times

**Comment by SushiBtw** [comment]
Fixed in v8.3.0, pushed per NPM - https://www.npmjs.com/package/discord-music-player/v/8.3.0.
