### ISSUE TITLE
Brick on Vevo music

### ISSUE THREAD

**Issue by SpeckyYT** [SushiBtw/discord-music-player#22]
When playing a copyrighted song (usually Vevo), the module doesn't play any music and when calling the "nowPlaying" function, it shows that it's the whole time stuck at 0:00.
Sometimes those songs work, sometimes they don't, idk.
![image of brick](https://media.discordapp.net/attachments/648254003519684628/785130561256554496/unknown.png)
![image of bot playing, but not playing](https://media.discordapp.net/attachments/648254003519684628/785131332152852480/unknown.png)
I'm not sure if that's even fixable, but I'm just reporting it.

**Comment by SushiBtw** [comment]
I will look into it.

**Comment by SushiBtw** [comment]
Live on https://www.npmjs.com/package/discord-music-player/v/6.3.0.
