### ISSUE TITLE
[BUG] Queue.seek() causing DMP to freeze.

### ISSUE THREAD

**Issue by ka0sdev** [SushiBtw/discord-music-player#224]
**Bug Description**
It seems when using queue.seek() to a timestamp above 20 minutes, it tends to freeze up the application, and rendering audio stream dead, and only way to recover is to /stop and then /play again.

**Reproduction Steps**
Make it play something like this; https://www.youtube.com/watch?v=xchCnyDyvVw and queue.seek into about 30 minutes, which renders the player unresponsive or frozen. 

**Expected Result**
It should seek into that point and continue to play. 

**Attachments**
First image shows, it's playing Parov Stelar - Megamix | Parov Stelar, then /seek is used, which is utilizing queue.seek(), I seek 30 minutes in, and then run /np to see now playing stats, it shows it's at 30:00/01:01:35.
![DMP1](https://user-images.githubusercontent.com/16397298/137038662-d37f8292-a8ce-43a8-9488-e9f6f976b546.png)

Second, I add another track to the playlist, and then run /skip which uses the queue.skip() function, then I run /np again to show now playing, however it has not skipped the track, and it remains on 30:00/01:01:35 from the first picture. Already here we can conclude that it's frozen.
![DMP2](https://user-images.githubusercontent.com/16397298/137038663-1a8fd8f4-0430-488c-8091-2588715c1316.png)

Third, I run /queue to view the current queue, from here I try to /skipto 1 utilizing queue.skip() and again I run /np to view now playing, but yet it is still stuck on the first track at 30:00/01:01:35
![DMP3](https://user-images.githubusercontent.com/16397298/137038665-57c31e93-42b7-4cce-8613-863f59e276a7.png)

**Versioning:**
- OS: CentOS 8 / Windows Server 2012
- Node Version: v16.10.0
- Module Version: 8.2.0

**Additional Comments**
It seems to work fine when it's at smaller timestamps between 1 minutes - 10 minutes.

**Comment by maxplayle04** [comment]
I've also encountered this!

**Comment by SushiBtw** [comment]
Hey, I can reproduce this issue, but after a short peroid of time - it loads the seek song! I will be looking into it to resolve the "await" time.

**Comment by ka0sdev** [comment]
> Hey, I can reproduce this issue, but after a short peroid of time - it loads the seek song! I will be looking into it to resolve the "await" time.

This is somewhat my experience as well, however based on my tests, it's very inconsistent how long the "await" time is, thanks for looking into it though! :)

**Comment by warior456** [comment]
guildqueu.nowplaying.millisecons is undefined now it used to work and i used it for check's in my seek command

**Comment by slienlaffa** [comment]
> guildqueue.nowplaying.millisecons is undefined now it used to work and i used it for check's in my seek command edit: mistyped guildqueue in my comment

someone changed to 'milliseconds' and didn't give notice of it, so you need to add that 'd'
