### ISSUE TITLE
[FR] Adding Queue Index as an optional parameter for the <Queue>.skip() method

### ISSUE THREAD

**Issue by AranyaMaji** [SushiBtw/discord-music-player#227]
Adding an index parameter to the `<Queue>.skip()` method would be ideal  as it would be a convenient and neat way to skip to and from a song anywhere in the queue. Making it an **optional parameter** would mean that if no parameters are provided, the player would skip to the next song, otherwise to the queue index provided.

**In Essence:** 
```js

// skipping to the next song (already a feature)
queue.skip();

// skipping to a song somewhere in the queue while shifting other songs accordingly (FR)
queue.skip(4)  // skipping to the 5th song in the queue
```

**Alternatively a `<Song>.jump(queueIndex)` could also be used to replicate this feature.**

**Comment by SushiBtw** [comment]
Good FR, will be adding!

**Comment by SushiBtw** [comment]
Added in https://www.npmjs.com/package/discord-music-player/v/8.3.0.

```js
<Queue>.skip(1);
```
