### ISSUE TITLE
[BUG] Event on.error fires two times

### ISSUE THREAD

**Issue by arhip144** [SushiBtw/discord-music-player#228]
Has anyone noticed that event `on.error` fires two times when errros is appears. For example video (https://www.youtube.com/watch?v=hc0ZDaAZQT0) gets an error `Status code: 410` and `on.error` triggers two times. Is there real bug or something in my code?
My code:
client.player.on('error', (error, queue) => {
      const song = queue.nowPlaying
      const channel = song.data.textChannel
      return channel.send({ content: 'error' })
})

**Comment by arhip144** [comment]
index.js

client.once("ready", async () => {
const modulesFiles = await globPromise(`${process.cwd()}/modules/*.js`);
        modulesFiles.map((value) => require(value)(client));
}

player.js

module.exports = async function (client) {
    client.player.on('songChanged', (queue, newSong, oldSong) => {
        const embed = new client.MessageEmbed()
        const channel = newSong.data.textChannel
        embed.setAuthor(`Сейчас играет`, channel.guild.iconURL(), newSong.url)
        embed.setTitle(newSong.name)
        embed.setURL(newSong.url)
        embed.setDescription(`Продолжительность: ${newSong.duration}`)
        embed.setFooter(`Запрос: ${newSong.requestedBy.username}#${newSong.requestedBy.discriminator}`)
        embed.setImage(newSong.thumbnail)
        return channel.send({ embeds: [embed] })
    })
    client.player.on('error', (error, queue) => {
        const song = queue.nowPlaying
        const channel = song.data.textChannel
        return channel.send({ content: `${client.config.emojis.NO} Произошла ошибка: ${error}, во время воспроизведения **${song.name}**. Трек пропущен.` })
    })
}

**Comment by Niekxd** [comment]
Same over here.

**Comment by SushiBtw** [comment]
Fixed via #239, push to npm today.

**Comment by SushiBtw** [comment]
Fixed in v8.3.0, pushed per NPM - https://www.npmjs.com/package/discord-music-player/v/8.3.0.
