### ISSUE TITLE
Bug with queue

### ISSUE THREAD

**Issue by sadorpl** [SushiBtw/discord-music-player#23]
[image](https://cdn.discordapp.com/attachments/784352920632164374/785763620982095912/unknown.png)
[image 2](https://cdn.discordapp.com/attachments/784352920632164374/785763999567970334/unknown.png)
[image 3](https://cdn.discordapp.com/attachments/784352920632164374/785764055457595392/unknown.png)

It returns undefined

**Comment by SpeckyYT** [comment]
Does any music play in the Vocal Channel?

**Comment by sadorpl** [comment]
> Does any music play in the Vocal Channel?

Yes

**Comment by SpeckyYT** [comment]
Over here it works without problems, so idk.

![IMG_20201208_083639.jpg](https://user-images.githubusercontent.com/40666126/101454022-966ef680-3930-11eb-9810-69143df2198b.jpg)

**Comment by sadorpl** [comment]
> Over here it works without problems, so idk.
> 
> ![IMG_20201208_083639.jpg](https://user-images.githubusercontent.com/40666126/101454022-966ef680-3930-11eb-9810-69143df2198b.jpg)

[video](https://cdn.discordapp.com/attachments/784352920632164374/785773137697701908/Film_08-40-27.mp4)

**Comment by sadorpl** [comment]
I fixed this, thanks 😂
