### ISSUE TITLE
[BUG] leaveOnEmpty not working while song playing

### ISSUE THREAD

**Issue by slienlaffa** [SushiBtw/discord-music-player#240]
**Bug Description**
If you leave the bot alone while playing a song or a playlist it will keep playing, even after it stops, will not disconnect until detecting some voice channel activity, with leaveOnEmpty set to true

**Reproduction Steps**
1. Reproduce a song
2. Leave the bot alone before it finishes the song
3. The bot will stay there

**Expected Result**
To leave on empty even if is playing something

**Comment by davidkhierl** [comment]
you need help with this @SushiBtw
