### ISSUE TITLE
[BUG] MODULE_NOT_FOUND in heroku

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#25]
**Bug Description**
in heroku i get this error err: MODULE_NOT_FOUND

**Reproduction Steps**
on heroku go to command line and run node . or npm start
it will give a error: err: MODULE_NOT_FOUND

**Expected Result**
i expected the bot to work because when i ran it off my computer it worked but on heroku it saes module not found.

**Attachments**

**Versioning:**
discord.js v.12
node v.12

**Additional Comments**

**Comment by SushiBtw** [comment]
Hello, have you installed the module?
```npm i discord-music-player```

**Comment by EclipseGame18** [comment]
the problem is fixed! thanks!
