### ISSUE TITLE
disconect command

### ISSUE THREAD

**Issue by HanifIskandar8** [SushiBtw/discord-music-player#250]
how to make a disconnect command from channel

**Comment by Extrymes** [comment]
If you set the `leaveOnStop: true` option, you can simply stop the music.

**Comment by AlphaRyz3** [comment]
U could just create a command passing in the current guildQueue in your command handler like this:
``JavaScript
let guildQueue = client.player.getQueue(message.guild.id)
await command.run(guildQueue, message, client, args) //Obviusly u gotta put all the part for the command handler
//In the Disconnect Commad u can just put a clearQueue() and a skip() to clear all the queue then as Extrymes said or u put the // leaveOnStop or u do a client.disconnect() kinda stuff
guildQueue.clearQueue()
guildQueue.skip()
``
