### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by Tabaluga113** [SushiBtw/discord-music-player#252]
Hi,

Um... this is probably real stupid, but how do i use a DMP command in other file than the main? Every time i tried i ended up getting: "Cannot read properties of undefined (reading 'setPaused)". It can be just a simple explanation. I'm new to this. 

Here is my code of the resume.js file. Help?

![image](https://user-images.githubusercontent.com/72629436/142930767-79b3aedd-0c56-4bae-9548-53798f8c611f.png)

**Comment by SpeckyYT** [comment]
so.... this isn't really a DMP related problem, but... if you insert the `guildQueue`, `Queue`, `Song`, `PlayOptions` and `player` values, you don't need to use the massive `require` on top of the file.
Also, this doesn't provide enough context, but where you call the callback, you should also insert the values, that's why it says `Cannot read properties of undefined`, since you probably didn't add them.

**Comment by Tabaluga113** [comment]
Okay, well... first of all, you may be right, it isn't DMP related problem, sorry for that, but it seems like the closest support i could find. 
Well second of all.... There isn't any context that's missing. The file above is the hole file. How do i make the music stop only using this file. The resume.js file, which isn't the main one. 
Would be grateful if you could precise what i should do? "insert the values" but what values if i want a "setPaused" function.

**Comment by SpeckyYT** [comment]
> but what values if i want a "setPaused" function.

_it should be obvious, since JavaScript is object oriented._

**Comment by Tabaluga113** [comment]
Yeah, still no clear answer. You realised, that i'm new to javascript, which is progress, but still you treat me like a developer. "It should be obvious". Shouldn't it be easier for you, and faster, to just give me an example solution, than to try to get me to do it myself?

I'm truly sorry for wasting your time. When/if you help me i'll send you a watermelon emoji. 

Maybe in fact you do need more context. Here is an image of my main file. Im using WOKCommands command handler. 

![image](https://user-images.githubusercontent.com/72629436/143059217-54e6c5a4-119b-43b4-87a6-dd868f559189.png)

Here is the top of the file, if you need it:

![image](https://user-images.githubusercontent.com/72629436/143059340-01e9b6c2-e93e-4b41-b5bb-705c6d7a1073.png)

And the resume,js file once again.

![image](https://user-images.githubusercontent.com/72629436/143059471-6fce16c4-ac7a-4d80-b775-769bd1459dbf.png)

And if you are going to answer, and not block me, cause im a retard, would love if you explained it like to a 5 year' old.

**Comment by SpeckyYT** [comment]
Ok, thanks for providing the needed context.
You can access to the player and queue by doing something like this in the command file
```js
callback: ({ client, message }) => {
  const { player } = client; // deconstruction syntax
  const guildQueue = player.getQueue(message.guild.id); // or "createQueue" if the queue in the guild doesn't exist (but since you're resuming, you're supposing that it already exists)

  guildQueue.setPaused(false)
}
```
this should in theory already be enough for it to work.

**Comment by Tabaluga113** [comment]
THANKS! And be sure i will learn from it. Here is the promised watermelon: 🍉
