### ISSUE TITLE
[BUG] Queue.playlist() causing a freeze

### ISSUE THREAD

**Issue by Extrymes** [SushiBtw/discord-music-player#253]
**Bug Description**
When DPM loads a Spotify or Apple Music playlist of more than about 50 songs, the bot crashes.

**Reproduction Steps**
1. Play a playlist with +50 songs.

**Expected Result**
The bot does not freeze.

**Versioning:**
- OS: Microsoft Windows 10
- Node Version: v16.13.0
- Module Version: 8.3.1

**Comment by slienlaffa** [comment]
It has something to do with fetching all the songs data, it probably should have a lower cap or maybe try to reduce the data per each song, I'm not sure

**Comment by Extrymes** [comment]
Yes I tried limiting the songs to 30 and it doesn't freeze anymore. But I wish I didn't need to set a limit...

**Comment by slienlaffa** [comment]
I tried with 250 and it limit me to 100, I don't in which part does it, it freezes for like 5 seconds, I only show 10 songs in queue, don't know if others show more than that

**Comment by Extrymes** [comment]
I don't think it's because it's getting the data for each song because with a youtube playlist it doesn't freeze. I think it comes from the fact that it searches every song in the playlist on youtube.

**Comment by slienlaffa** [comment]
I know what I can do, I'll set a 25 behind the scenes limit, so will only look up 25 youtube songs, then when it is around 20 songs search for the next 25. People will have to change the way they show the number of songs in a playlist, probably add the number in the event. At least for Spotify, not sure if can do the same in apple music

**Comment by Extrymes** [comment]
Yes, it can be a good solution :)

**Comment by SushiBtw** [comment]
I will still be looking into improving the playlist util.

**Comment by SushiBtw** [comment]
Fix loads in v10.
