### ISSUE TITLE
[BUG] Unable to Play YT or Spotify Link Songs

### ISSUE THREAD

**Issue by AlphaRyz3** [SushiBtw/discord-music-player#254]
**Bug Description**
After using a play command for only songs if u try to use the normal search for songs it gives back a result while using a Youtube or Spotify Link it doesn't and it just ignores it not giving even the Queue has Ended event as back it just triggers the catch istantly since yesterday, and i didn't change anything on the relative code. I even tried to remove the catch part but still it doesn't work. In attachment my code example

**Reproduction Steps**
1. To replicate the bug just go to the [link here](https://pastebin.com/AKCBhTqL) and copy the code from line.40 to line.60 and put it inside a normal play command 
2. Observe the result.

**Expected Result**
Searching for Songs it Plays it while Using a Link it Skips Directly to the queue.stop()

**Attachments**

**Versioning:**
- OS: Microsoft Windows 11
- Node Version V16.10.0
- Module Version 8.1.3

**Comment by AlphaRyz3** [comment]
By the way that's the same play command code as the Documentation One

**Comment by slienlaffa** [comment]
I will say, a silent catch is a bad practice, you are getting an exception, you should print the error

**Comment by AlphaRyz3** [comment]
I don get anything, just the song doesnt play

**Comment by slienlaffa** [comment]
Does every link fail? youtube explicit videos may fail because of the age restriction
 
Still don't know how to reproduce the problem.

**Comment by AlphaRyz3** [comment]
Yes it fails with every single link

**Comment by slienlaffa** [comment]
It's your code is the problem, for example ` const arg = message.content.slice(prefix.length).trim().split(/ +/g);` you split it, but never remove the prefix, I tried it and it gives a pseudo random song

**Comment by AlphaRyz3** [comment]
oooow i totally ignored that part cause i thought it was another kinda problem ty so much
