### ISSUE TITLE
[FR] Add guildQueue.isPaused

### ISSUE THREAD

**Issue by DEVTomatoCake** [SushiBtw/discord-music-player#256]
**Is your feature request related to a problem? Please describe.**
Its easier to get a boolean instead of manually setting it in the data object.

**Describe the solution you'd like**
A boolean that returns true if the current queue is paused, and false if not.

**Comment by SpeckyYT** [comment]
`<Queue>.paused` already exists

**Comment by DEVTomatoCake** [comment]
![image](https://user-images.githubusercontent.com/60300461/144494832-deafaf44-7c2d-4153-a25a-c0cd4725c126.png)
Then it doenst display in the docs

**Comment by DEVTomatoCake** [comment]
Oh nvm I was on the development branch, its on the master branch
Maybe remove the development branch if it isnt actively used to avoid things like this.
Thanks!
