### ISSUE TITLE
[BUG] Short bug description

### ISSUE THREAD

**Issue by UntaEffect** [SushiBtw/discord-music-player#260]
How do i fix this?

node_modules\discord-music-player\dist\managers\Queue.js:117
                throw new __1.DMPError(__1.DMPErrors.VOICE_CONNECTION_ERROR);
                      ^

DMPError [VoiceConnectionError]: There was an Error while starting the Voice Stream

**Comment by UntaEffect** [comment]
nvm i fix it :" sorry

**Comment by 69u** [comment]
How did you fix this got the exact error right now,,,

**Comment by SushiBtw** [comment]
Add Voice intents to your client.

**Comment by 69u** [comment]
forgot to mention voice intent is already enabled as well as ffmpeg-static being installed.

![image](https://user-images.githubusercontent.com/36492979/147357207-7019456a-fcdd-4169-b3ce-24414810f9e4.png)

**Comment by 69u** [comment]
> Add Voice intents to your client.

never mind. was due to the bot lacking permission to join the channel. This should be stated more clearly...

**Comment by SushiBtw** [comment]
I will state it more clearly next update, thanks for letting me know.

**Comment by 69u** [comment]
> I will state it more clearly next update, thanks for letting me know.

no stress cheers for being awesome
