### ISSUE TITLE
[BUG] Queue.shuffle() doesn't work

### ISSUE THREAD

**Issue by bop34** [SushiBtw/discord-music-player#263]
**Bug Description**
Queue.shuffle doesn't work, throwing an error

**Reproduction Steps**
1. Use Queue.shuffle()

**Expected Result**

**Attachments**

**Versioning:**
- OS: Ubuntu 20.04.3
- Node Version v16.13.0
- Module Version 8.3.1

**Additional Comments**
Error logs:
`0|index    |     at WebSocketShard.onMessage (/home/bop34/BopBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)

0|index    |     at WebSocket.onMessage (/home/bop34/BopBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)

0|index    |     at WebSocket.emit (node:events:390:28)

0|index    |     at Receiver.receiverOnMessage (/home/bop34/BopBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:1022:20)

0|index    | TypeError: Cannot read properties of undefined (reading 'shuffle')

0|index    |     at Client.<anonymous> (/home/bop34/BopBot/index.js:141:14)

0|index    |     at Client.emit (node:events:390:28)

0|index    |     at MessageCreateAction.handle (/home/bop34/BopBot/node_modules/discord.js/src/client/actions/MessageCreate.js:25:14)

0|index    |     at Object.module.exports [as MESSAGE_CREATE] (/home/bop34/BopBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)

0|index    |     at WebSocketManager.handlePacket (/home/bop34/BopBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)

0|index    |     at WebSocketShard.onPacket (/home/bop34/BopBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)

0|index    |     at WebSocketShard.onMessage (/home/bop34/BopBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)

0|index    |     at WebSocket.onMessage (/home/bop34/BopBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)

0|index    |     at WebSocket.emit (node:events:390:28)

0|index    |     at Receiver.receiverOnMessage (/home/bop34/BopBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:1022:20)
`

**Comment by SpeckyYT** [comment]
Reminder: normally in js, variables that start with an uppercase letter (CamelCase), like Queue, are mostly probably Classes (cause of the naming convention).
The Queue class doesn't have a static method called "shuffle", but it does have a prototype method named "shuffle", which means that you can only call "shuffle" from instances.

**Comment by SushiBtw** [comment]
Seems your Queue is undefined. Not a DMP issue.
