### ISSUE TITLE
[BUG] Immediate song playing doesn't work

### ISSUE THREAD

**Issue by Skiroe** [SushiBtw/discord-music-player#267]
**Bug Description**
 Immediate song playing doesn't work. If you try to play a song and give a options object with immediate : true to the play command, the play command doesnt play the song, but just starts the current playing song again.

**Reproduction Steps**
await guildQueue.play(previousSong, {immediate : true})
This code doesnt play the previous song, but just starts the current song again (it doesnt matter what the previousSong is).

**Expected Result**
The given song to the play command to play, instead of the current playing song.

**Versioning:**
- OS: [Windows 11]
- Node Version [v16.5.0]
- Module Version [e.g v8.2.0]

**Comment by SushiBtw** [comment]
immediate option is not an option that should be given by you, it's used via the bot after a song ended.

**Comment by Skiroe** [comment]
Ah okay I see, but isn't there a way to play a song immediatly? (While there are others songs in the queue).

**Comment by elbkr** [comment]
the play function has an option to add the song to a specific index. Make queue.play(song, {index: 0}) and then skip the current song queue.skip()

This should work
