### ISSUE TITLE
[FR] Timeout for exiting the vocal channel

### ISSUE THREAD

**Issue by SpeckyYT** [SushiBtw/discord-music-player#27]
**Is your feature request related to a problem? Please describe.**
If the "leaveOnEmpty" or the "leaveOnEnd" are enabled, then the bot instantly leaves once that criteria is met, but it would be really nice to have a settable timeout for when at least one of the "leaveOn" conditions are triggered.

**Describe the solution you'd like**
It would be really nice to have a "timeout" parameter on setting up the music player.
The timeout's default value could be 0.
```js
    new Player(
        client,
        {
            leaveOnEmpty: true,
            leaveOnEnd: true,
            timeout: 60000 // 60 seconds (or "timeoutOnExit", idk)
        }
    )
```

**Additional Comments**
Obviously, if the "leaveOnEnd" option is enabled and the queue is empty, then if the users play another song in less than 60 seconds, the bot won't leave the voice channel, and the same with "leaveOnEmpty".

**Comment by ArmyaAli** [comment]
I agree, I use this library too for my bot and that would be an excellent QoL update!

**Comment by SushiBtw** [comment]
Good FR, adding this to [v6.3.0 Update](https://github.com/SushiBtw/discord-music-player/pull/26). I started working on it.

**Comment by SushiBtw** [comment]
Live on https://www.npmjs.com/package/discord-music-player/v/6.3.0.
