### ISSUE TITLE
[BUG] Youtube Livestreams stops after 5-10 seconds

### ISSUE THREAD

**Issue by iLazlow** [SushiBtw/discord-music-player#270]
**Bug Description**
It seems that Livestreams of Youtube dont work as correctly. After 5-10 seconds the bot stops and the queue is finished. I did some digging and it seems like it is a problem of yt-dl (https://github.com/fent/node-ytdl-core/issues/1015). It is not really a problem within yt-dl itself, more a problem of youtube. There is like a solution (https://github.com/fent/node-ytdl-core/issues/925#issue-899618391). Can anybody confirm if i am correct?

**Reproduction Steps**
Play a YouTube Livestream link

**Expected Result**
Livestream should work continually

**Versioning:**
- OS: Windows 11
- Node Version v16.6.0
- Module Version v8.3.1

**Comment by warior456** [comment]
after a bit of digging there is a setting somewhere where you should change the livebuffer to 4900 for livestreams to work
