### ISSUE TITLE
[feature request] add remove duplicates

### ISSUE THREAD

**Issue by warior456** [SushiBtw/discord-music-player#273]
Can you add queue.removeduplicates?
Or does anyone know how i do it without this?

**Comment by SpeckyYT** [comment]
> Can you add queue.removeduplicates?
> Or does anyone know how i do it without this?

```js
const uniques = []
queue.songs.filter((song, i) => uniques.inludes(song.url) ? true : (uniques.push(song.url), false))

queue.songs = uniques
```

something like this
