### ISSUE TITLE
[BUG] queue.play() with immediate option

### ISSUE THREAD

**Issue by Jogeer** [SushiBtw/discord-music-player#278]
**Bug Description**
1. When you try to add a song to an empty queue immediately (immidate option), you get a TypeError [on this line](https://github.com/SushiBtw/discord-music-player/blob/884e428bf127de43fe84e642e43062a256678b08/src/managers/Queue.ts#L218).
```
TypeError: Cannot read properties of undefined (reading 'seekTime')
    at Queue.play (...\node_modules\discord-music-player\dist\managers\Queue.js:197:18)
```

2. The situation when you try to add a song to a non-empty queue with the same options:
Ex.: in current server queue: `Song 1, Song 2`.
You are trying to add `Song 3` and play immediately. Ideally, the song should play immediately, and `Song 1` and `Song 2` are moved down in the queue. But after adding `Song 3` it immediately skips (I'm not sure what's going on here) and `Song 1` starts playing from the beginning.

**Reproduction Steps**
Both situations can be reproduced as follows:
1. Try to add a song to a queue with `immidate` option:
`queue.play(url, { immediate: true });`
2. Grab the error.

**Expected Result**
The song was successfully added and started playing.

**Versioning:**
- OS: Windows 11 build 22000.593
- Node Version: v16.14.2
- Module Version: ^8.3.2

**Comment by warior456** [comment]
with immediate is it to instantly load the url into the queue?

**Comment by SushiBtw** [comment]
immediate is a private option
