### ISSUE TITLE
[Songs not playing] despite doing /play and /playlist nothing plays

### ISSUE THREAD

**Issue by DevBungfro** [SushiBtw/discord-music-player#279]
**Bug Description**
When i try to do my commands the bot does not play music, this was working fine up until a few hours ago. Now it joins the chanel but doesn't play anything, there are also no errors in console

**Expected Result**
I expected it to start working and playing the music, it was working fine and then all of sudden it doesn't wanna play anything.

**Attachments**

**Versioning:**
- OS: Ubuntu 18.04

**Comment by warior456** [comment]
is this still ongoing?
