### ISSUE TITLE
[BUG] AbortError

### ISSUE THREAD

**Issue by Pqoh** [SushiBtw/discord-music-player#281]
**Bug Description**
It happens every time I play a song .

**Reproduction Steps**
1. /play <song> with a code equal to the one you provided
2. the bot enters the channel and plays the song, but returns this error

**Expected Result**
play normally without returning errors? 

**Attachments**
![Screenshot_20220526-171552_Chrome](https://user-images.githubusercontent.com/48698601/170573816-60b986e1-0cf0-4c1d-bf45-2b89ffd52d4f.png)

**Versioning:**
- OS: [e.g. Ubuntu 18.04]
- Node Version [e.g. v16.6.0]
- Module Version [e.g v6.2.0]

**Additional Comments**

**Comment by SushiBtw** [comment]
fixed by djs
