### ISSUE TITLE
[BUG] bot getting kicked after a while

### ISSUE THREAD

**Issue by warior456** [SushiBtw/discord-music-player#285]
**Bug Description**
the bot gets kicked after a while of playing music

**Reproduction Steps**
1. load a big playlist
2. wait
3. get an error : i was kicked from the voice channel, queue ended (in audit log there is no proof of it being kicked)

**Expected Result**
music should keep playing

**Attachments**

**Versioning:**
- OS: [e.g. Ubuntu 18.04]
- Node Version [e.g. v16.6.0]
- Module Version [7]

**Comment by warior456** [comment]
i'm guessing this might be to do with discord timeout

**Comment by dionsyran2** [comment]
Either it overloaded and quit trying to load the playlist or it took so much time that discord kicked it, discord does this if a bot is inactive in a vc for some time

**Comment by warior456** [comment]
it was still playing altough the green bar was no longer visible

**Comment by SushiBtw** [comment]
Can not reproduce.
