### ISSUE TITLE
[FR/question]

### ISSUE THREAD

**Issue by warior456** [SushiBtw/discord-music-player#286]
**Is your feature request related to a problem? Please describe.**
I have an array of youtube links and currently i have to add them all with queue.play() wich is extremely slow
is there a faster way to do this?

**Describe the solution you'd like**
I would like a way to add an array of 100 youtube links to the queue in about 5 seconds instead of 100

I need to do this because of a loadqueue feature in my bot wich loads a saved playlist to the queue

**Comment by SushiBtw** [comment]
Fix loads in v10.
