### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jurgenjacobsen** [SushiBtw/discord-music-player#29]
**Bug Description**
Usually when I try playing some live stream, my bot accepts the request and start playing, after 5 seconds it stops play but doesn't says any error on the console

**Versioning:**
 - OS: Node v14.15.1
 - NPM Version: v6.14.8
- Module Version: v6.2.0

**Additional Comments**
I love your package, it has been helping me a lot lately

**Comment by SushiBtw** [comment]
Hey, I can reproduce this issue, I am not sure if it's YouTube intended, but I will look into it.

**Comment by jurgenjacobsen** [comment]
Thanks man, merry christmas for you, I hope you can find the problem.

**Comment by SushiBtw** [comment]
We still does not support streams, but I will try to look into this issue today.
