### ISSUE TITLE
[QUESTION] Adding cookies for age restricted tracks?

### ISSUE THREAD

**Issue by Onegenimasu** [SushiBtw/discord-music-player#291]
Greetings.

I would like to ask how to make playing age restricted tracks possible.

As of now, playing age restricted tracks will throw an `Status code: 410` error. I was able to handle that error just by using the player error event and notify users about the problem, but I would like to be able to play restricted tracks as well, if it is even possible.

While looking up the issue, I found something about using [addons](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/)/[extensions](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/) to extract a cookies.txt file from YouTube, which are then *somehow* passed to YTDL. Apart from using [a command option](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl), I wasn't able to find a guide/example/usage/... about how to pass the file to YTDL - maybe only [this](https://github.com/fent/node-ytdl-core/issues/661#issuecomment-652584008), but what were the passed values? (I don't have experience with YTDL directly, which is why the confusion..my apologies...).

So, I'm asking - how can I make age restricted videos available in my DMP-using bot? If it's these cookies I mentioned, how do I extract them and pass them to the bot/player/ytdl/...?

Thank you very much for any answers.

**Comment by SushiBtw** [comment]
Will fully support in v10.

**Comment by SushiBtw** [comment]
![image](https://user-images.githubusercontent.com/45533122/188330472-1c144a5f-5114-479b-b0c4-7e48eb40d38a.png)
Using cookies in v9.
