### ISSUE TITLE
[GitHub Page] About section only saying "discord.js v13"

### ISSUE THREAD

**Issue by ASPNyan** [SushiBtw/discord-music-player#294]
The about section on this github page only says `Complete framework to facilitate music commands using discord.js v13` and not `Complete framework to facilitate music commands using discord.js v14 & v13`, or something similar

Just thought that you might've forgotten to change it since the readme.md says **`Note: This is the v9 version of Discord Music Player for Discord.JS v14 & v13!`**

**Comment by SushiBtw** [comment]
Thank you
