### ISSUE TITLE
[FR] Filter (Bass boost, 8D, and more)

### ISSUE THREAD

**Issue by Xapu1337** [SushiBtw/discord-music-player#30]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
An function like [`setFilter`](https://github.com/Androz2091/discord-player/blob/master/src/Player.js)
to add filter like bass boost and more. Would be an Awesome addiction!

**Comment by SushiBtw** [comment]
I am looking for this, you can now use [Play Options](https://github.com/SushiBtw/discord-music-player#documentation) that are listed bellow to filter the search:
```js
{
	uploadDate: 'hour/today/week/month/year', // Default - none
	duration: 'short/long', // Default - none
	sortBy: 'relevance/date/view count/rating' // Default - 'relevance'
}

// Example
Player.play('This is the life', {
	duration: 'long'
});
```

I am planning to add a such function. Thanks for the Feedback!

**Comment by SpeckyYT** [comment]
@SushiBtw he doesn't mean "searching filters", he means "sound filters", like "bass boost", "vibrato", "8D", etc

**Comment by SushiBtw** [comment]
I see now, my bad. That's a good FR, I will be going to add it.

**Comment by Xapu1337** [comment]
yep, sorry i did an error yes. search filter would also nice!
and if you are able to set an max video length to block videos with an specific legth.
like > 10 min will be aborted.

**Comment by SushiBtw** [comment]
Sure, I will add it to my board too.

**Comment by SushiBtw** [comment]
Out of scope per now, will get back to it in later 7.3.0/7.4.0.
