### ISSUE TITLE
[BUG] Unhandled error. ('Invalid or unexpected token')

### ISSUE THREAD

**Issue by Eithoo** [SushiBtw/discord-music-player#302]
**Bug Description**
It suddenly stopped working - now bot can't play music in the voice channel.

**Reproduction Steps**
Just try to play music.
Tested on [Eithoo/dsc-spotify_follower](https://github.com/Eithoo/dsc-spotify_follower), which was working fine for a couple of months.

**Attachments**
![image](https://user-images.githubusercontent.com/62159998/186797825-cfa22054-6012-4d0c-a48c-4488b7b8f9d1.png)

**Versioning:**
- OS: Ubuntu 20.04.4 LTS (WSL), Windows 10, Docker with Nodejs v16 (tested in a few environments)
- Node Version: v16.14.2
- Module Version: 8.3.2, 9.0.0, 9.0.2

**Comment by dionsyran2** [comment]
I had the same problem, I fixed it by updating ytdl-core
run `npm i ytdl-core@latest`

**Comment by SushiBtw** [comment]
Fixed in https://www.npmjs.com/package/discord-music-player/v/9.1.1
