### ISSUE TITLE
[BUG] spotify playlist not working at all

### ISSUE THREAD

**Issue by warior456** [SushiBtw/discord-music-player#303]
**Bug Description**
when providing a spotify playlist it doesn't recognize it as a valid playlist
**Reproduction Steps**
1. try to do the playlist command to add a spotify playlist

**Expected Result**
the playlist get's added to the queue (preferably more than 100 on spotify)

**Attachments**

**Versioning:**
- OS: windows 10
- Node Version 16
- Module Version 9.0.2

**Comment by warior456** [comment]
```
nvalidPlaylist: There was no Playlist found with that link.
    at H:\discordbot\mrdia-main\node_modules\discord-music-player\dist\managers\Queue.js:271:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Queue.playlist (H:\discordbot\mrdia-main\node_modules\discord-music-player\dist\managers\Queue.js:269:24)
    at async playlist (H:\discordbot\mrdia-main\src\Commands\music\playlist.js:26:20)
```

**Comment by revathiest** [comment]
Repeated

- OS: Windows 11
- Node Version 17.9.1
- Module Version 9.0.2

**Comment by SushiBtw** [comment]
Fix today!

**Comment by SushiBtw** [comment]
Fix live, thank you!
https://www.npmjs.com/package/discord-music-player/v/9.1.0
