### ISSUE TITLE
Unwanted console.log while using the playlist function [BUG]

### ISSUE THREAD

**Issue by NiinaDev** [SushiBtw/discord-music-player#32]
Firstly, I want to say is that it's not really a bug but it might be something that is unwanted.

So, whenever you use the `client.player.playlist()` function, it will `console.log()` an array of all videos in the playlist. This code can be found on `line 213` of `Util.js`. Again, I don't know if this is intentional or just left there after the testing stages and I will be removing it from my side because it is just flooding my console with things I don't need. In my opinion, it should be removed since the module is made for discord bots, and flooding your console with unwanted things is just something that should be avoided.

**Comment by SushiBtw** [comment]
Hey, thanks for reporting this, I removed the console logging - that was due testing.
I already published a small fix update [v6.3.2](https://www.npmjs.com/package/discord-music-player/v/6.3.2).

That should avoid this.
