### ISSUE TITLE
[BUG] Bot exits after playing ~30sec of music.

### ISSUE THREAD

**Issue by TheLegendOfWolf** [SushiBtw/discord-music-player#323]
When using !play, bot leaves the channel after ~30sec-1min. Bot doesn't crash, only leaves the channel.

Accessing the issue: 
1. Use !play command with song you like
2. Wait

Latest Version and lower ones.

This is probably problem created by discord (attachment)

Is it possible to fix it by myself, or i need to wait?

Also, bot doesn't throw any error. I once got "aborted" error but never again.

Have a nice day :)

![obraz_2023-03-06_182428473](https://user-images.githubusercontent.com/52168178/223184809-b36958e9-3566-48b6-991b-4b79f9e0be6c.png)

**Comment by Im-HaGGling** [comment]
Hello, I am experiencing similar behavior and also receiving an error after the bot leaves the channel.
```
AbortError: The operation was aborted
    at abortListener (node:events:970:14)
    at AbortSignal.<anonymous> (node:events:1006:47)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:585:26)
    at abortSignal (node:internal/abort_controller:291:10)
    at AbortController.abort (node:internal/abort_controller:322:5)
    at Timeout.<anonymous> (/home/ftp/zbots/Discord/Mcskill/NewYearRadio/node_modules/@discordjs/voice/dist/index.js:1991:39)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at new DOMException (node:internal/per_context/domexception:70:5)
      at AbortController.abort (node:internal/abort_controller:320:18)
      at Timeout.<anonymous> (/home/ftp/zbots/Discord/Mcskill/NewYearRadio/node_modules/@discordjs/voice/dist/index.js:1991:39)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
}
```
My code:
![image](https://user-images.githubusercontent.com/78200999/223192236-beb4180b-2594-4b70-b6b2-5f25b9ff2d1f.png)

**Comment by aierwin** [comment]
I had this issue, If you add the following solution after line 162 of the /src/managers/Queue.js file fixes it. This is where I found it https://github.com/SushiBtw/discord-music-player/pull/322.

```
connection.on('stateChange', (oldState, newState) => {
            const oldNetworking = Reflect.get(oldState, 'networking');
            const newNetworking = Reflect.get(newState, 'networking');
          
            const networkStateChangeHandler = (_oldNetworkState, newNetworkState) => {
                const newUdp = Reflect.get(newNetworkState, 'udp');
                clearInterval(newUdp?.keepAliveInterval);
            }
          
            oldNetworking?.off('stateChange', networkStateChangeHandler);
            newNetworking?.on('stateChange', networkStateChangeHandler);
 });
```

**Comment by TheLegendOfWolf** [comment]
> I had this issue, If you add the following solution after line 162 of the /src/managers/Queue.js file fixes it. This is where I found it #322.
> 
> ```
> connection.on('stateChange', (oldState, newState) => {
>             const oldNetworking = Reflect.get(oldState, 'networking');
>             const newNetworking = Reflect.get(newState, 'networking');
>           
>             const networkStateChangeHandler = (_oldNetworkState, newNetworkState) => {
>                 const newUdp = Reflect.get(newNetworkState, 'udp');
>                 clearInterval(newUdp?.keepAliveInterval);
>             }
>           
>             oldNetworking?.off('stateChange', networkStateChangeHandler);
>             newNetworking?.on('stateChange', networkStateChangeHandler);
>  });
> ```

Thank you so much! It worked!
For other ones if you struggle to do this 
Open the bot folder, enter into node modules, find discord music player, enter, enter dist enter managers and open Queue.js

Now you need to find the line **126**, it should start with "selfDeaf", after the "});" copy and paste the code that nice fellow posted above me :), save, run the bot and check if it is working!

**Comment by SushiBtw** [comment]
Thank you @acousticorangutan - this will have a fix on my side:)

**Comment by davidpr0811** [comment]
I Don't work in my bot but i have the change

**Comment by Link0Darck** [comment]
it doesn't work either on my side the music works for 30 seconds and it stops

I'm not sure if it's a good idea to use the same software as the one I'm using now, but I'm not sure if it's a good idea to use the same software as the one I'm using now.

**Comment by securing-ab** [comment]
I haven’t tested it myself but a few hours ago djs released a new update for their voice package. Consider updating it as it might fix your issue

**Comment by Link0Darck** [comment]
> I haven’t tested it myself but a few hours ago djs released a new update for their voice package. Consider updating it as it might fix your issue

I said it's ok it works I had a bug and then it's ok it works 😺

**Comment by K-Tamas01** [comment]
When will it fix? Because, I Can't edit files on hosting server.
