### ISSUE TITLE
[BUG] Spotify links are giving an error that are crashing the bot. (Also some youtube searches)

### ISSUE THREAD

**Issue by Xapu1337** [SushiBtw/discord-music-player#33]
**Bug Description**
If someone submits an spotify link the bot will crash.
`Error: search string is mandatory
`

**Reproduction Steps**
If you have an play command just execute an spotify link.
something like:
`https://open.spotify.com/track/698ItKASDavgwZ3WjaWjtz?si=zu9_cbHnS5agMJ3j_yeAJw`

**Expected Result**
I dont expect anything. maybe just an "SearchIsNull" error.

**This happens also with non spotify links. idk how but this happends. an youtube result with the german letter "ß" crashed it last time.**

**Versioning:**
 - OS: Windows 10
 - NPM Version 7.0.14
- Module Version v6.3.0

**Additional Comments**
*While testing:*
it played an youtube song. idk how but it did so its not everytime crashing. just finding an youtube song with anything acsociated with the link.

**Comment by SushiBtw** [comment]
Seems that my manager is not detecting it, I will look for it later tomorrow and release a hotifx as soon as I found and resolve this issue.

**Comment by Xapu1337** [comment]
```
C:\Users\XapuR\OneDrive\Rom\node_modules\discord-music-player\src\node-ytsr-wip\utils.js:90
    throw new Error('search string is mandatory');
          ^

Error: search string is mandatory
    at Object.exports.checkArgs (C:\Users\XapuR\OneDrive\Rom\node_modules\discord-music-player\src\node-ytsr-wip\utils.js:90:11)
    at AsyncFunction.main.getFilters (C:\Users\XapuR\OneDrive\Rom\node_modules\discord-music-player\src\node-ytsr-wip\main.js:100:21)
    at C:\Users\XapuR\OneDrive\Rom\node_modules\discord-music-player\src\Util.js:118:54
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

```
full trace

**Comment by SushiBtw** [comment]
Thanks for it.

**Comment by NiinaDev** [comment]
Tried using the same link you provided, nothing went wrong. Even tried some other song links and everything worked as intended.

**Comment by NiinaDev** [comment]
> **Bug Description**
> If someone submits an spotify link the bot will crash.
> `Error: search string is mandatory `
> 
> **Reproduction Steps**
> Steps to reproduce the behavior:
> If you have an play command just execute an spotify link.
> something like:
> `https://open.spotify.com/track/698ItKASDavgwZ3WjaWjtz?si=zu9_cbHnS5agMJ3j_yeAJw`
> 
> **Expected Result**
> I dont expect anything. maybe just an "SearchIsNull" error.
> 
> **This happens also with non spotify links. idk how but this happends. an youtube result with the german letter "ß" crashed it last time.**
> 
> **Versioning:**
> 
> * OS: Windows 10
> * NPM Version 7.0.14
> * Module Version v6.3.0
> 
> **Additional Comments**
> _While testing:_
> it played an youtube song. idk how but it did so its not everytime crashing. just finding an youtube song with anything acsociated with the link.

Tried using the same link you provided, nothing went wrong. Even tried some other song links and everything worked as intended.

**Comment by Xapu1337** [comment]
did it play an youtube song?
try more. some not so known songs.

**Comment by NiinaDev** [comment]
> did it play an youtube song?
> 
> try more. some not so known songs.

Yes, I have tried multiple sorts of tracks. Send some of your code, maybe the issue is somewhere there?

**Comment by Xapu1337** [comment]
What version are you using?
and maybe try an command where you do an args .join(" ");

here is currently my code:
```
const getQueueEmbed = async () => {
            let queue = await client.player.getQueue(message.guild.id);
            let ql = (queue.songs.map((song, i) => {
                return `${i === 0 ? 'Now Playing' : `\`#${i+1}\``} - \`${song.name}\`${song.author.name ?  ` | \`${song.author.name}\`` : ""}`
            })).join("\n");
            // let splittedEmbedFor = splitStringBySegmentLength(ql, 1024);
            // let spliited = [];
            // for(let i = 0; i < spliited.length; i++){
            //     spliited.push(ql.substr(0, 1024))
            // }
            // console.log(spliited);
            let embed =  new MessageEmbed()
                .setColor(await client.getColorFromUserId(message.member))
                .setFooter(`A request from: ${message.author.username}`)
                .setTimestamp()
                .setThumbnail(message.author.displayAvatarURL())
                .setDescription(ql.length >= 2048 ? "Splitting into fields..." : ql);
            if(ql.length >= 2048){
                let qql = ql.convertStringToArray(1024);
                qql.forEach(i => {
                    embed.addField(client.charList.EMPTY, i);
                });
            }
            return embed;
        };
        if(!message.member.voice.channel){
            message.reply("You aren't in an Voice channel.");
            return;
        }
        if(!message.member.voice.channel.joinable){
            message.reply("Couldn't join. (Missing permissions?)");
            return;
        }
        if(message.member.voice.channel.full){
            message.reply("Your channel is full. Can't join.");
            return;
        }
        // if(args.includes("spotify.com")){
        //     message.reply("Spotify links are broken. they are crash the bot.");
        //     return;
        // }
       try{
           if (client.player.isPlaying(message.guild.id)) {
               await client.player.addToQueue(message.guild.id, args.join(" "), {duration: 'short'}, message.member).then(async song => {
                   if (song.error) throw(song.error);
                   message.channel.send(`Added: \`${song.song.name}\` to the queue.`);
                   await message.channel.send(await getQueueEmbed());
               }).catch(err => {
                   if(err.type === "SearchIsNull"){
                       message.reply("Nothing found. please search again. or provide an link.");

                   } else {
                       client.logError(message, "Error while executing the play command...", err)
                       console.log(err)
                   }
               });
           } else {
               await client.player.play(message.member.voice.channel, args.join(" "), {duration: 'short'}, message.member).then(async song => {
                   if (song.error) throw(song.error);
                   message.channel.send(`Playing: \`${song.song.name}\``);
                   try{
                       await message.channel.send(await getQueueEmbed());
                   } catch (e) {
                       console.log(e);
                   }
               }).catch(err => {
                   if(err.type === "SearchIsNull"){
                       message.reply("Nothing found. please search again. or provide an link.");

                   } else {
                       client.logError(message, "Error while executing the play command...", err)
                       console.log(err)
                   }
               });
           }
       } catch (e) {
           console.log(e);
           message.reply("Please try it again.");
       }

```

**Comment by Xapu1337** [comment]
the try catch was for testing.
didn't worked, the bot still crashed.

**Comment by NiinaDev** [comment]
Have you tried without any options?

**Comment by SushiBtw** [comment]
I can not reproduce this issue.
DMP is looking if the argument is not a string per:
```js
 if (typeof songName !== 'string' || songName.length == 0) return new MusicPlayerError('SongTypeInvalid', 'song');
 ```
 
 Can you debug your ``args.join(" ")`` please? Also, as @NiinaDev said, try removing the **Options**.

**Comment by SushiBtw** [comment]
I just pushed a [v6.3.3 Update](https://www.npmjs.com/package/discord-music-player/v/6.3.3), can you please check if the issue still persists.

**Comment by Xapu1337** [comment]
Everything is fixed.
thanks ^^
