### ISSUE TITLE
Queue Loop [FR]

### ISSUE THREAD

**Issue by NiinaDev** [SushiBtw/discord-music-player#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use the `toogleLoop()` for a queue loop

**Describe alternatives you've considered**
Make a new function for queue loop

**Additional Comments**
None

**Comment by SushiBtw** [comment]
The full queue? Yeah, I am working on it.

**Comment by NiinaDev** [comment]
Thank you
