### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ToledoSDL** [SushiBtw/discord-music-player#36]
**Bug Description**
The playlist mode didn't work

**Reproduction Steps**
1. Use this playlist url: https://www.youtube.com/watch?v=IM-rp-wAgaw&list=RDIM-rp-wAgaw
2. Observe the result.

**Expected Result**
Play the playlist

**Attachments**
![image](https://user-images.githubusercontent.com/65132614/102831141-cc4cba00-43c9-11eb-93a8-de0c0e69e3aa.png)

**Versioning:**
 - OS: Windows 10
 - NPM Version [e.g. v6.14.8]
- Module Version [e.g v6.3.2]

**Comment by SushiBtw** [comment]
We only support the global playlist links, but I will try do do my best and support YouTube links from videos in the playlist.

You can now use the ``https://youtube.com/playlist?list=...`` links, but I am adding this to my board and working on it.

Thanks for the report.

**Comment by NiinaDev** [comment]
That seems like an error in your code, you are probably trying to access a property of the object the wrong way. The link you provided worked with my code.

**Comment by SushiBtw** [comment]
Hello, I checked the valid links, and the valid playlist links are working:
```ascii
https://www.youtube.com/watch?v=bvC_0foemLY&list=PLm08aPBt0KkPGu681mclK3VUZZToW08M5
https://www.youtube.com/playlist?list=PLm08aPBt0KkPGu681mclK3VUZZToW08M5
```

For the link you provided, that's a local playlist, that we can not have access to.
Using that link you will get a **MusicPlayerError** that will return this data:
```js
MusicPlayerError {
  error: {
    type: 'InvalidPlaylist',
    message: 'No Playlist was found with that link.'
  },
  song: null,
  playlist: null
}
```
We can only support public playlists, from watch or playlist endpoints that have the ``list`` query with **34** playlist ID characters length *(Public Playlists)*.

As @NiinaDev said, that's a problem with your code (you are trying to access the Playlist that is null). You can avoid it by adding a line to your code:
```js
let playlist = await client.player.playlist(message.guild.id, args.join(' '), message.member.voice.channel);

// Check for errors.
if(playlist.error) return message.channel.send(playlist.error.message || 'No Playlist was found.');

...
```

*I will be updating the README to add this short catch error code.*

**Comment by SushiBtw** [comment]
Open this issue if you have more questions.
