### ISSUE TITLE
[FR] "RequestedBy" param for playlists

### ISSUE THREAD

**Issue by Chappy202** [SushiBtw/discord-music-player#39]
**Is your feature request related to a problem? Please describe.**
Currently, the playlist() function does not have a "RequestedBy" parameter, resulting in the RequestedBy selector in messages being displayed as "Undefined".

**Describe the solution you'd like**
I'd like the ability to pass the "RequestedBy" through the playlist() function, so that it can also be used in messages and other places in the same way you would the one from play(). For example:
With song you would usually use it like this in an embed:
`.setFooter(`Requested by: ${song.requestedBy}`)`
I'd like to have the same capabilities from the playlist function.

**Describe alternatives you've considered**
I've tried using the "RequestedBy" from the song object, but that also resulted in "undefined" if the song was added through the playlist player. I am however able to use my own function, but this resulted in a less modular system. It would be better to also have this be integrated into the package.

**Comment by SushiBtw** [comment]
Hey, thanks for notifying me, I updated the package to v6.3.5 - https://www.npmjs.com/package/discord-music-player/v/6.3.5

You can now use:
```js
client.player.playlist(GuildID, PlaylistURL, VoiceChannel, MaxSong, RequestedBy);
```
