### ISSUE TITLE
link support

### ISSUE THREAD

**Issue by Aduzy** [SushiBtw/discord-music-player#4]
there is no youtube link support?

**Comment by SushiBtw** [comment]
Hey! There is support for YouTube links.
We are aware, that some links may not show the correct result, but it's being fixed in v5.0.5 (that will go out tomorrow).

You can use song link/name:
```js
client.player.play(voiceChannel, songName);
```

**Comment by Aduzy** [comment]
weird

returned an error but now it works, i don't know why ...

anyway closing the problem thanks
