### ISSUE TITLE
Playlist return undefined data[BUG]

### ISSUE THREAD

**Issue by NiinaDev** [SushiBtw/discord-music-player#42]
**Bug Description**
The playlist object returns `undefined` for `requestedBy` property

**Reproduction Steps**
1. use the `playlist()` function
2. give the bot a playlist URL
3. `console.log()` the result

**Expected Result**
The discord tag of the requester

**Attachments**
https://i.imgur.com/gZYy7LH.png

**Versioning:**
 - OS: Windows 10
 - NPM Version: v6.14.8
- Module Version: v6.3.0

**Additional Comments**
None

**Comment by SushiBtw** [comment]
Hey, I can reproduce this issue, I will send a fix update for it tomorrow!

Thanks for the report.
