### ISSUE TITLE
[BUG] SyntaxError: Unexpected token ; in JSON at position 70064

### ISSUE THREAD

**Issue by sadordev** [SushiBtw/discord-music-player#43]
**Versioning:**
 - OS: Ubuntu latest
 - NPM Version latest

![Zrzut ekranu 2020-12-27 140931](https://user-images.githubusercontent.com/58658387/103171504-2bd51a80-484d-11eb-8a9a-31709125d307.png)

**Comment by SushiBtw** [comment]
Hey, what are you trying to run?

**Comment by sadordev** [comment]
> Hey, what are you trying to run?
> 
> Also please provide the Module Version.

latest version
I get this error when I run the play command with a link to an unpublic song, works with normal songs

**Comment by SushiBtw** [comment]
Working on a fix.
