### ISSUE TITLE
[BUG] Playlist function returns empty queue

### ISSUE THREAD

**Issue by CeaserPlayz** [SushiBtw/discord-music-player#45]
**Bug Description**
When using the playlist() function, sometimes it does not recognise the playlist or recognises it but it returns an empty queue where playlistSongs is an empty array.

**Reproduction Steps**
1. Use playlist() function with the code supplied in documentation.
2. console.log() the result.

**Expected Result**
Should have added all the songs in the playlist to the queue.

**Attachments**
![image](https://user-images.githubusercontent.com/66173114/103280854-50ee9800-49c9-11eb-91a0-f947e978ee13.png)
![image](https://user-images.githubusercontent.com/66173114/103280504-7dee7b00-49c8-11eb-9e3b-278208b9da6a.png)
![image](https://user-images.githubusercontent.com/66173114/103280769-1553ce00-49c9-11eb-91d0-497f578d67cf.png)

**Versioning:**
 - OS: Windows 10 Pro
 - NPM Version v6.14.8
- Module Version Latest (v6.3.5)

**Additional Comments**
I'm not sure if I have worded it very well so if you need more clarification please tell me.

**Comment by SushiBtw** [comment]
Working on a fix.

**Comment by SushiBtw** [comment]
Fixed in #52 - live on NPM.
