### ISSUE TITLE
[BUG] Bot is playing music even if user has changed voice chat

### ISSUE THREAD

**Issue by xIgreq** [SushiBtw/discord-music-player#47]
**Bug Description**
Bot is playing music even if user has changed voice chat

**Reproduction Steps**
1. Play any type of music
2. Change voice channel
3. (You can leave channel) wait some of time
4. (Connect again to any channel where bot isn't and) move to channel with bot
5. You can hear, that bot is playing.

**Player Settings**
```
        {
            leaveOnEnd: true,
            leaveOnStop: true,
            leaveOnEmpty: true,
            timeout: 1000,
            quality: 'high'
        }
```

**Versioning:**
 - OS: Windows 10
 - NPM Version v6.14.9
 - Module Version v6.3.5
 - Discord.js v12.5.1
 - opusscript v0.0.7

**Comment by SpeckyYT** [comment]
I noticed this issue too.

**Comment by SushiBtw** [comment]
I can reproduce this issue, I started working on a global fix per most of issues and I will provide a update asap.
