### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by DashCruft** [SushiBtw/discord-music-player#5]
Hey guys! I hope ya all doing good.
I wanted to request a progress method. it creates a progress bar and yeah. 
Here is an example:

bot.player.createProgressBar(message.guild.id)

![image](https://user-images.githubusercontent.com/59381835/99485645-b4d86800-2917-11eb-9ff4-cfd56800920e.png)

**Comment by SushiBtw** [comment]
Hey!

Thank you for the suggestion, yes we are going to add something like this.

Thanks!

**Comment by DashCruft** [comment]
Awesome! Looking forward to it.

**Comment by SushiBtw** [comment]
Hello sir! This feature is under development and will be released in one week (v6.0.0).

Thank you for your suggestion!

**Comment by SushiBtw** [comment]
We started working on it per #13.

**Comment by SushiBtw** [comment]
**This suggestion was implemented in [v6.0.0 Update](https://www.npmjs.com/package/discord-music-player/v/6.0.0).**

Thank you for the suggestion.
