### ISSUE TITLE
[FR] Seek method

### ISSUE THREAD

**Issue by kekn9ne** [SushiBtw/discord-music-player#50]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Seeking method is needed, i think. Example: ``client.player.seek(guild_id, "0:30");``

**Comment by SushiBtw** [comment]
Hey, what would it do? Jump to the time you provide?

**Comment by kekn9ne** [comment]
> Hey, what would it do? Jump to the time you provide?

Yes, exactly.
