### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Leonardo-ST** [SushiBtw/discord-music-player#53]
**Discord-music-player has this error:**

![1611398912032](https://user-images.githubusercontent.com/70207858/105576128-76b05800-5d4f-11eb-90fb-371e6c0bc51e.png)

**Comment by SushiBtw** [comment]
Can you update NodeJS to >14?

**Comment by Leonardo-ST** [comment]
in node version is 12.16.1 the npm does not work?

**Comment by SpeckyYT** [comment]
This got fixed in #52, but it didn't got published to npm yet.

**Comment by SushiBtw** [comment]
I am going to push it today.

**Comment by Leonardo-ST** [comment]
it's okay

**Comment by SushiBtw** [comment]
Fixed in #52 - live on NPM.
