### ISSUE TITLE
[FR] Default Volume

### ISSUE THREAD

**Issue by EvasiveXkiller** [SushiBtw/discord-music-player#55]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A default volume when defining in options. Ex : 
```
const player = new Player(client, {
	volume : 100
});
```

**Comment by SushiBtw** [comment]
Sure, adding it to #54 - update in this week

**Comment by EvasiveXkiller** [comment]
Thanks! Much appreciated

**Comment by SushiBtw** [comment]
Wooops - didn't closed with #54 🤦 

The volume option is live on https://www.npmjs.com/package/discord-music-player/v/6.4.0
