### ISSUE TITLE
[FR] Check if player is in the same voicechannel as the bot

### ISSUE THREAD

**Issue by MilleniumModsSources** [SushiBtw/discord-music-player#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
That's pretty much it, probably this is already possible but I'm dumb and, yea, check if the command author (aka. player) is in the same channel as the bot.

**Comment by SushiBtw** [comment]
Hey, you can do it by yourself using the following statement:
```js
if(client.player.getQueue(message.guild.id).connection.channel.id === message.member.voice.channelID)
{
    // Same Voice Channel
}
```

**Comment by SpeckyYT** [comment]
![IMG_20210129_104950](https://user-images.githubusercontent.com/40666126/106259758-efb42180-621f-11eb-87d2-c2b56cc16db7.jpg)
This is how I solved this problem on my bot.

**Comment by SushiBtw** [comment]
We won't be providing support for those functions that can be made locally.
Just use the code above or @SpeckyYT's one.

**Comment by SushiBtw** [comment]
Closed - Resolved [Not A FR]
