### ISSUE TITLE
Music Queue

### ISSUE THREAD

**Issue by DashCruft** [SushiBtw/discord-music-player#6]
Hey!

In the queue command, it should list the songs that are in the queue.
However, it shows the current playing song too. I don't want that to happen. I want it to only show the queue.
Code:

    const queue = await bot.player.getQueue(message.guild.id);
    if (!queue) return message.channel.send('> :notes: Nothing in queue!')
    const embed = new Discord.MessageEmbed()
        .setTitle(`🎶 **Current Queue**`)
        .setDescription(`${(queue.songs.map((songs, i) => {
            return `${`\`${i + 1}\``} | \`(${songs.duration})\` **${songs.name}** - ${songs.requestedBy}`;
        }).join('\n'))}`)
    let stuff = await message.channel.send(embed)

As mentioned, Only the queue should show up, Not the current playing song.

**Comment by SushiBtw** [comment]
Can you try using ``queue.shift();`` after the definition? Please update me, if it works!

**Comment by DashCruft** [comment]
Where specifically you want me to put that?

**Comment by SushiBtw** [comment]
After ``if (!queue) return message.channel.send('> :notes: Nothing in queue!')``.

**Comment by DashCruft** [comment]
I've received an error:
![image](https://user-images.githubusercontent.com/59381835/99890219-dbe1b300-2c11-11eb-8316-a50d6312cefa.png)

**Comment by SushiBtw** [comment]
Hey, sorry for the wrong code - it would be ``queue.songs.shift();`` :D

**Comment by DashCruft** [comment]
I did. And now it doesn't show anything on the list.

**Comment by SushiBtw** [comment]
That's probably due one song on the list.

**Comment by SushiBtw** [comment]
Closing as resolved.
