### ISSUE TITLE
[BUG] Seek function not working

### ISSUE THREAD

**Issue by MilleniumModsSources** [SushiBtw/discord-music-player#60]
**Bug Description**
Okay so, I was testing the seek function and I cannot find a way to make it works, even tried using the example code and it simply doesn't work.

**Reproduction Steps**
1. Make the bot play a song
2. Run seek command
3. Error: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null 
4. With some code modifications, the error becomes: "<client>.player.seek is not a function"

**Expected Result**
Seek to the provided second of the song.

**Attachments**
Video:
https://drive.google.com/file/d/13Ll7RG_Id50jbsGjujU64GjAnX3w1GQ0/view

**Versioning:**
 - OS: Windows 10
 - NPM v14
- Module Version: 6.3.7

**Comment by SushiBtw** [comment]
Hey, seems that your ``message.args`` in seek.js is undefined. Can you check it?

**Comment by MilleniumModsSources** [comment]
Tried setting only "args[0]", still doesn't work

**Comment by SushiBtw** [comment]
What's the error (can you send it here) then?

**Comment by MilleniumModsSources** [comment]
This is the full error:

(node:14464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.module.exports.run (C:\Users\marti\OneDrive\Escritorio\Luxury Bot\Luxury-2\Luxury-1\commands\music\seek.js:26:81)
    at Client.<anonymous> (C:\Users\marti\OneDrive\Escritorio\Luxury Bot\Luxury-2\Luxury-1\bot.js:112:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.

This is the code (using command handlers):
```
 const Discord = require("discord.js")
//const config = require("../config.json")

module.exports.run = async (bot, message, args) => {

    const voiceChannel = message.member.voice.channel;
    const botVoiceChannel = message.guild.me.voice.channel;
    
    if (voiceChannel.id != botVoiceChannel.id) {
        const embedshare = new Discord.MessageEmbed()
        .setTitle('Error')
        .setColor('RED')
        .setDescription("You need to be in the same channel as Luxury to seek in music!")
        .setFooter(`Requested By: ${message.author.tag} | Guild: ${message.guild.name}`, message.author.avatarURL())
        message.channel.send(embedshare);
    } 
    
    if(!args[0]) {
        const embed0 = new Discord.MessageEmbed()
        .setTitle('Error')
        .setColor('RED')
        .setDescription('Usage: -seek <Amount> <s (seconds) / m (minutes) / h (hours)>') //fix this, ashley :D
        message.channel.send(embed0)

    } else if (!args[1]) {
        let song = await bot.player.seek(message.guild.id, parseInt(message.args[0] * 1000));
        const embed1 = new Discord.MessageEmbed()
        .setTitle('Seek')
        .setColor('BLUE')
        .setDescription(`Seeked to ${message.args[0]} second of ${song.name}.`)
        message.channel.send(embed1)

    } else if (args[1] === 's'){
        let song = await bot.player.seek(message.guild.id, parseInt(message.args[0] * 1000));
        const embed2 = new Discord.MessageEmbed()
        .setTitle('Seek')
        .setColor('BLUE')
        .setDescription(`Seeked to ${message.args[0]} second of ${song.name}.`)
        message.channel.send(embed2)

    } else if (args[1] === 'm'){
        let song = await bot.player.seek(message.guild.id, parseInt(message.args[0] * 60000));
        const embed3 = new Discord.MessageEmbed()
        .setTitle('Seek')
        .setColor('BLUE')
        .setDescription(`Seeked to ${message.args[0]} minute of ${song.name}.`)
        message.channel.send(embed3)

    } else if (args[1] === 'h') {
        let song = await bot.player.seek(message.guild.id, parseInt(message.args[0] * 360000));
        const embed4 = new Discord.MessageEmbed()
        .setTitle('Seek')
        .setColor('BLUE')
        .setDescription(`Seeked to ${message.args[0]} hour of ${song.name}.`)
        message.channel.send(embed4)

    }
}

module.exports.help = {
            name: "seek",
            aliases: ["se"]
        };
```

**Comment by SushiBtw** [comment]
I told you, ``message.args`` is undefined. Try using ``args`` without ``message``, i.e:
```js
args[0]
```

**Comment by MilleniumModsSources** [comment]
Omg I dumb, I did that but wasn't working (Not sure why but installed the package again and they did) so I just set them as message.args
