### ISSUE TITLE
[BUG] - player song changed event

### ISSUE THREAD

**Issue by FearOfficial** [SushiBtw/discord-music-player#62]
**Bug Description**
Whenever calling the 
`client.player.getQueue(message.guild.id)
                    .on('songChanged'....`
                    
Where 'name' is being called:
```message.channel.send(`Ended playing ${oldSong.name}! Now playing ${newSong.name}!`);```

Putting one song in queue breaks this and crashes the bot with the error "Cannot read property 'name' of undefined"

**Reproduction Steps**
1. Use the following code, and queue one song:
*Of course include the backticks in .setDescription, i removed them here for formatting purposes*
> 
> client.player.getQueue(message.guild.id)
>                     .on('songChanged', (oldSong, newSong, skipped, repeatMode, repeatQueue) => {
>                         const songChangedEm = new MessageEmbed()
>                             .setTitle('<:TickYes:594764024864833547> | Next Song')
>                             .setAuthor(message.author.tag)
>                             .setDescription(🎶 - Now Playing: **${newSong.name}**)
>                             .setColor(ok_color)
>                         message.channel.send(songChangedEm)
>                     });

**Expected Result**
It would skip this event because the song isnt 'changing'.

**Attachments**
![image](https://user-images.githubusercontent.com/42700057/106674976-312b3080-6582-11eb-9528-1a881dfc2438.png)

**Versioning:**
 - OS: Windows 10 Pro, V.2004
 - NPM Version v6.14.10
- Module Version @latest

**Comment by SushiBtw** [comment]
Can you add the ```js
if(!newSong || oldSong) return;```
string in the `songChanged` method? Also, it shouldn't fire the songChanged method when there is only one song playing? Can you include what steps and commands do you fire?

**Comment by SushiBtw** [comment]
This BUG was marked as **FIXED** in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player
