### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jurgenjacobsen** [SushiBtw/discord-music-player#65]
**Bug Description**
First time I play something it plays OK, but when the queue ends it doesnt actually clear or stop the queue, so my song ends and when I play something else it shows that the song was added to the playlist but never plays.

The queue never actually clears after the end.

**Expected Result**

**Versioning:**
 - NPM Version [e.g. v6.14.9]
- Module Version [e.g v6.4.0]

**Comment by jurgenjacobsen** [comment]
And also even the queue finish the isPlaying function shows as true, but should be false.

**Comment by SushiBtw** [comment]
Looking into it.

**Comment by SushiBtw** [comment]
Should be fixed in the last PR #73, I will push the changes to NPM in 1-2 days.
