### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sajjadmrx** [SushiBtw/discord-music-player#69]
![Screenshot from 2021-02-14 04-32-51](https://user-images.githubusercontent.com/66132114/107865758-53c12180-6e7f-11eb-8430-ba584aa42696.png)
why? :|

**Comment by SushiBtw** [comment]
This BUG was marked as **FIXED** in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player
