### ISSUE TITLE
Play Error

### ISSUE THREAD

**Issue by Aduzy** [SushiBtw/discord-music-player#7]
### So im getting this error once im trying to play a song

_(node:12880) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input     
    at JSON.parse (<anonymous>)
    at module.exports (D:\path\to\bot\node_modules\discord-music-player\src\ytsearch\main.js:24:37)_

Any ideas how can i fix it? Or should i wait for an update

**Comment by SushiBtw** [comment]
Hello, thank you for the report.

We are working on a fix, to resolve the issue.

**Comment by SushiBtw** [comment]
This issue was resolved in the newest update (v5.0.5). Thank you for reporting it.

Module Update: https://www.npmjs.com/package/discord-music-player/v/5.0.5
GitHub Update: https://github.com/SushiBtw/discord-music-player/commit/24954b92e23213ade5b24ad55ddc2084d36043fd
