### ISSUE TITLE
Loop queue not working

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#71]
The loop queue command does not work and it gave me a error message.

I did the code correctly and ran the bot and the bot started and when I use the loop queue command it gave me a error message on the console 

This is the error: ``UnhandledPromiseRejectionWarning: TypeError: client.player.setQueueRepeatMode is not a function``

- discord.js version 12
- Module Version  v6.4.0

**Comment by SushiBtw** [comment]
Hey, I will check it out today.

**Comment by EclipseGame18** [comment]
thanks and btw I am using Heroku to host the bot :)

**Comment by SushiBtw** [comment]
This BUG was marked as **FIXED** in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player
