### ISSUE TITLE
[FR] Support for Spotify Playlists

### ISSUE THREAD

**Issue by jackdevey** [SushiBtw/discord-music-player#72]
**Is your feature request related to a problem? Please describe.**
Playing a single track from Spotify through YouTube works great however is there a way for this to also work for Spotify playlists or albums?

**Describe the solution you'd like**
If the URL provided points towards a Spotify playlist, loop through each track inside of it and add it's YouTube equivalent to the queue.

**Describe alternatives you've considered**
This could possibly be achieved using Spotify's REST API, which has an endpoint for seeing the items of a Spotify playlist [here](https://developer.spotify.com/console/get-playlist-tracks/).

**Additional Comments**
n/a

**Comment by SetaWinsU** [comment]
it would be great if the autor could do that

**Comment by SushiBtw** [comment]
Sure, I will look into it (I can scrape it so no tokens needed).

@SetaWinsU What do you mean by that?

**Comment by SetaWinsU** [comment]
@SushiBtw I mean add the support for spotify playlists (sry for my english btw im Spanish xD)

**Comment by SushiBtw** [comment]
Yes, I will be adding this!

**Comment by SushiBtw** [comment]
This FEATURE REQUEST was added in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player

**Comment by jackdevey** [comment]
This is great thanks!
