### ISSUE TITLE
[BUG]bot entering and leaving the room

### ISSUE THREAD

**Issue by valseftw** [SushiBtw/discord-music-player#75]
I am using windows server 2012 r2 system
bot entering and leaving the room
this is video

https://user-images.githubusercontent.com/48654905/108953715-b33be000-767c-11eb-8f50-85e13a0b8bf3.mp4

**Comment by SushiBtw** [comment]
Are you sure someone did not disconnected it? I cannot reproduce it.

**Comment by valseftw** [comment]
yes sir i am sure, nobody disconnects the bot.
I can run it on my own computer, but when I put it on a server, it doesn't work like in the video.

**Comment by SushiBtw** [comment]
This BUG was marked as **FIXED** in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player
