### ISSUE TITLE
[FR] Skips to prev song

### ISSUE THREAD

**Issue by EvasiveXkiller** [SushiBtw/discord-music-player#76]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
A method to skip to the previous song

**Comment by SpeckyYT** [comment]
With the current system it isn't really possibile, since when it ends a song, the song gets deleted from the queue. There should be made a major rework to the queues to make this.

**Comment by EvasiveXkiller** [comment]
I see. Thanks!
