### ISSUE TITLE
[BUG] Live video causes invalid time value

### ISSUE THREAD

**Issue by EvasiveXkiller** [SushiBtw/discord-music-player#77]
**Bug Description**
Attempting to play a live video causes the play() method to return an unhandled promise rejection.

**Reproduction Steps**
1. Play any live video with a link from YouTube OR search a live video.
2. Error is thrown.

**Expected Result**
The player plays and no error is returned. 

**Attachments**
```
thread_music: (node:21056) UnhandledPromiseRejectionWarning: RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at getVideoDuration (E:\github\diit\diitbot\node_modules\discord-music-player\src\Util.js:41:25)
    at E:\github\diit\diitbot\node_modules\discord-music-player\src\Util.js:108:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Versioning:**
 - NPM Version [e.g. v6.14.8]
- Module Version [6.4.1]
- ytdl-core [4.5.0]

**Additional Comments**
 A catch block has no effect on catching the error.

**Comment by SushiBtw** [comment]
This BUG was marked as **FIXED** in the V.7.0.0 update.
https://www.npmjs.com/package/discord-music-player
