### ISSUE TITLE
[BUG] Live video plays then stops

### ISSUE THREAD

**Issue by EvasiveXkiller** [SushiBtw/discord-music-player#80]
**Bug Description**
If a live video link is played, the music plays for about 5 seconds then it stops. There are no errors thrown. The bot still functions as normal as adding tracks to queue and skipping tracks function normally.

**Reproduction Steps**
1. Play a live video link from YouTube with either the play() or addToQueue() function.
2. The song plays momentarily.
3. The song stops

**Expected Result**
The music continues to play

**Versioning:**
- Module Version : 7.0.0

**Additional Comments**
No other error is thrown. If other functions like skip() are used, it skips the current song and continues to play the next song in the queue.

**Comment by SushiBtw** [comment]
We don't support live streams, I will add a error handler for it

**Comment by SushiBtw** [comment]
I released a `v7.0.0-fix1` update on NPM, that will emit a `Player#error` with a `LiveUnsupported` error parameter ([check events](https://github.com/SushiBtw/discord-music-player#events)).

https://www.npmjs.com/package/discord-music-player
