### ISSUE TITLE
[BUG] While trying to start the music stream, an unhandled error occurs for "isLive" and for ".url" both belonging to undefined variable song.

### ISSUE THREAD

**Issue by kaly666** [SushiBtw/discord-music-player#82]
**Bug Description**
`song` variable seems to be undefined at line 820. First it will return error while checkinf if "isLive" , and if I comment that part it will return error because it cannot read property url of undefined (song).

**Reproduction Steps**
1. Used play function from the documentation
2. await client.player.play(message, args.join(' '))

**Expected Result**
Music should start playing

**Attachments**

**Versioning:**
 - OS: Windows
 - NPM Version 6.14.8
- Module Version 7.0.0 bugfix1

**Additional Comments**
Looks like the bugfix didn't fix the issue.

**Comment by SushiBtw** [comment]
Hey, what are you trying to play?

**Comment by SushiBtw** [comment]
Also does the addSong gets emitted?

**Comment by kaly666** [comment]
Any song I'm trying to play would result in the unhandled error.

**Comment by kaly666** [comment]
`Started playing B.U.G. Mafia - Strazile feat. Mario V (Prod. Tata Vlad) (Videoclip)
(node:1612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isLive' of undefined
    at Player._playSong (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\node_modules\discord-music-player\src\Player.js:822:17)
    at StreamDispatcher.<anonymous> (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\node_modules\discord-music-player\src\Player.js:857:29)
    at StreamDispatcher.emit (events.js:327:22)
    at finish (_stream_writable.js:657:10)
    at finishMaybe (_stream_writable.js:644:9)
    at _stream_writable.js:617:7
    at StreamDispatcher._final (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:248:5)
    at callFinal (_stream_writable.js:610:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:1612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`
Here is the console output.

**Comment by kaly666** [comment]
If I try to comment the "isLive" check , the the error will be related to url of song.

**Comment by SushiBtw** [comment]
I will look into it, can you show me your ``Player`` config and `play` method?

**Comment by kaly666** [comment]
It's mostly default
```
const player = new Player(client, {
    leaveOnEnd: false,
    leaveOnStop: false,
    leaveOnEmpty: true,
    timeout: 0,
    volume: 150,
    quality: 'high',
});```

```
       
        var args = message.content.slice(1).trim().split(/ +/g);
      
        let isPlaying = client.player.isPlaying(message.guild.id);

        if(isPlaying){
            let song = await client.player.addToQueue(message.guild.id, args);
            song = song.song;
            return message.say(`Song ${song.name} was added to the queue!`);
        } else {

            let song = await client.player.play(message.member.voice.channel, args);
            song = song.song;
            return message.say(`Started playing ${song.name}!`);
        }```

**Comment by SushiBtw** [comment]
can you change `args` to `args.join(' ')` and remove the `song.song` thing (docs changed)?

**Comment by kaly666** [comment]
I've sent the wrong play method. sorry.
```
        const args = message.content.slice(1).trim().split(/ +/g);

        if(client.player.isPlaying(message)) {
            let song = await client.player.addToQueue(message, args.join(' '))
                .catch(error => {
                    return message.channel.send(error.message);
                });

            console.log(`Added ${song.name} to queue`);
            return;
        } else {
            let song = await client.player.play(message, args.join(' '))
                .catch(error => {
                    return message.channel.send(error.message);
                });

            console.log(`Started playing ${song.name}`);
            return;
        }
```

**Comment by SushiBtw** [comment]
Okay thanks! I will look into it, have you tried spotify songs/links/search? Every option does not works?

**Comment by kaly666** [comment]
I only tried with words. I will try links now.

**Comment by kaly666** [comment]
On youtube links same issue related to "isLive" and then to url.

For soundcloud links:
```
(node:5084) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async Object.execute (C:\Users\Kaly\Documents\NodeJs\Discord Bots\Work In Progress\Work Projects\bot updated\commands\musicCommands\v1play.js:21:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by SushiBtw** [comment]
Okay, last things - if you use `play()` does the `Player#songAdd` event get's emitted for you? If yes, please send the `Queue` result from it here.

**Comment by kaly666** [comment]
I sent a friend request on discord. I am not very familiar with it and I don't undestand what d oyou mean about " `Player#songAdd` event get's emitted "

**Comment by cawarduck** [comment]
Hello. I have the same issue at the end of  playback.
_Uncaught TypeError: Cannot read property 'isLive' of undefined_
also even if playback is runnig the method **isPlaying**  allways returns FALSE
the thing is  that somehow curren queue doesn't save after playback is started .  and **this.queues** remains empty when any command calls to it. so **queue** and  **song** instances becomes undefined

**Comment by SushiBtw** [comment]
Can I get your both NodeJS and NPM versions?

**Comment by cawarduck** [comment]
npm version 6.14.6
node js version v12.18.3

**Comment by kaly666** [comment]
node : v14.15.1
npm : v6.14.8

**Comment by cawarduck** [comment]
sorry for that, it was my stupid mistake - every time i called play method  I declared a new instance of Player, thats why queues was empty))
now it works fine.
anyway i found that mistake ( _Cannot read property 'isLive' of undefined_) when queue ends and player options have leaveOnEnd : false. In that case at the end of the queue fires 'songChanged' event and and fires an arror

**Comment by AMDBartek** [comment]
Can confirm, I am also getting this issue.

**Comment by Alexmdz77** [comment]
I also have this issue when the sound ends :
```js
TypeError: Cannot read property 'isLive' of undefined
 at Timeout._onTimeout (/root/bots/calypso/node_modules/discord-music-player/src/Player.js:824:21)
 at listOnTimeout (internal/timers.js:549:17)
 at processTimers (internal/timers.js:492:7)
```
And the bot crash.

**Player config :**
```js
client.player = new Player(
	client, 
	{
		leaveOnEnd: false,
		leaveOnStop: true,
		leaveOnEmpty: true,
		timeout: 15000,
		quality: 'high'
	}
);
```

**Versioning :**
- Node v12.18.2
- Npm v6.14.7
- discord-music-player v7.0.0-fix3

**Comment by SushiBtw** [comment]
Strange issue, I am still investigating the issue, I can not find the reason why it happens.

**Comment by 4Lajf** [comment]
I can cofrim that the issue still exists when the song ends.
`TypeError: Cannot read property 'isLive' of undefined
    at Timeout._onTimeout (C:\Users\SzK\Documents\DBM\Karren\node_modules\discord-music-player\src\Player.js:824:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)`
or when you try to play a livestream
`TypeError: Cannot read property 'isLive' of undefined
    at Timeout._onTimeout (C:\Users\SzK\Documents\DBM\Karren\node_modules\discord-music-player\src\Player.js:824:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)`

**Versioning:**

    Node v15.12.0
    Npm 7.6.3
    discord-music-player@7.0.0-fix3

**Comment by zKryle** [comment]
I get the same error.. also it logs in the console: "Started playing undefined", then the bot joins and i get this error:
`TypeError: Cannot read property 'isLive' of undefined
    at Timeout._onTimeout (C:\Users\ciro2\OneDrive\Desktop\Programmazione\Bottazzo Sgravato Experimental\node_modules\discord-music-player\src\Player.js:824:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by SushiBtw** [comment]
I am working on a `v7.0.1` update dropping today! Fix incoming.

**Comment by SushiBtw** [comment]
Hey! Update time!
I hope everything got fixed, please check within `v7.0.1` and let me know!
https://www.npmjs.com/package/discord-music-player

Thank you for the patience,
Sushi!

**Comment by Alexmdz77** [comment]
Hi, I still have a problem with this:
When a song ends, it stays in the queue and when I !play another song it doesn't start until I do !leave

What I would like is that the bot stays in the channel but that the queue is empty

**Player config :**
```js
client.player = new Player(
	client, 
	{
		leaveOnEnd: false,
		leaveOnStop: true,
		leaveOnEmpty: true,
		timeout: 15000,
		quality: 'high'
	}
);
```

**Versioning :**
```js
Node v12.18.2
Npm v6.14.7
discord-music-player v7.0.0-fix3
```

**Comment by Alexmdz77** [comment]
(there is no error displayed) I don't know if I should reopen an issue...

**Comment by SushiBtw** [comment]
Its happening due ``Options#leaveOnEnd: false``. Not needed, I will work on it.
