### ISSUE TITLE
TypeError: `[object Object]` is not an Option Object

### ISSUE THREAD

**Issue by SuperSweatyTejas** [SushiBtw/discord-music-player#83]
Just getting this wen i run my bot using this module

heres my index.js code

const fs = require('fs');
const discord = require('discord.js');

const client = new discord.Client({ disableMentions: 'everyone' });

const { Player } = require("discord-music-player");

const player = new Player(client, {
    leaveOnEmpty: false, 
});

client.player = player;

client.commands = new discord.Collection()

fs.readdirSync('./commands').forEach(dirs => {
    const commands = fs.readdirSync(`./commands/${dirs}`).filter(files => files.endsWith('.js'));

    for (const file of commands) {
        const command = require(`./commands/${dirs}/${file}`);
        console.log(`Loading command ${file}`);
        client.commands.set(command.name.toLowerCase(), command);
    };
});

const events = fs.readdirSync('./events').filter(file => file.endsWith('.js'));

for (const file of events) {
    console.log(`Loading discord.js event ${file}`);
    const event = require(`./events/${file}`);
    client.on(file.split(".")[0], event.bind(null, client));
};

client.login(process.env.TOKEN);

**Comment by SushiBtw** [comment]
I am working on a `v7.0.1` update dropping today! Fix incoming.

**Comment by SushiBtw** [comment]
Hey! Update time!
I hope everything got fixed, please check within `v7.0.1` and let me know!
https://www.npmjs.com/package/discord-music-player

Thank you for the patience,
Sushi!
