### ISSUE TITLE
[BUG] ERR_UNHANDLED_ERROR

### ISSUE THREAD

**Issue by AlexandreSama** [SushiBtw/discord-music-player#86]
**Bug Description**
When i try to play a song, the bot join the channel but don't speak. After 10 seconds, he crash with this error !

**Expected Result**

**Attachments**
![Capture](https://user-images.githubusercontent.com/56075082/112224302-66233d80-8c2b-11eb-9c3b-0afca7201f6f.PNG)
![Capture2](https://user-images.githubusercontent.com/56075082/112224306-67ed0100-8c2b-11eb-88ad-92e53c5dcf5a.PNG)

**Versioning:**
 - OS: Windows 10
 - NPM Version 7.6.3
- Module Version 7.0.1

**Additional Comments**

That's WEIRD !

**Comment by SushiBtw** [comment]
Can you send me the `.vscode/launch.json` file?

**Comment by AlexandreSama** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\main.js"
        }
    ]
}

**Comment by AlexandreSama** [comment]
basic, I don't have a launch.json file, I just do F5 then I select NodeJs to launch the bot

**Comment by SushiBtw** [comment]
Are you debugging or launching the project?

**Comment by AlexandreSama** [comment]
I debug the project

**Comment by Bxzzy** [comment]
this also happens to me, any fix found?

**Comment by AlexandreSama** [comment]
Well, not really... When i recreate a project (from the start), it work again !
