### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by Bxzzy** [SushiBtw/discord-music-player#93]
**Is your feature request related to a problem? Please describe.**
Do you have a Discord server for this module? its a really nice one and it would really benefit users who need direct support either with you or other staff/helpers/any one else.

**Describe the solution you'd like**
A discord support server

**Describe alternatives you've considered**
I understand they can make bug and FR issues but a server would be easier with the ability to reach everyone else that has used your module.

**Comment by SpeckyYT** [comment]
This is the official Discord Server of this module: https://ssumbot.xyz/discord
