### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by Bxzzy** [SushiBtw/discord-music-player#95]
**Is your feature request related to a problem? Please describe.**
Ability to play spotify playlists? 

**Describe the solution you'd like**
Same way how youtube playlists work but accept spotify playlist links!

**Describe alternatives you've considered**
I was going to work on grabbing every single song from a Spotify playlist link and then querying it thru YT to play thru voice chat but im sure others would also enjoy this feature as part of the module.

**Comment by SpeckyYT** [comment]
lol

**Comment by Bxzzy** [comment]
> lol

im a little slow 😔
