### ISSUE TITLE
[FR] Youtube link support

### ISSUE THREAD

**Issue by Z3T4C0DE** [SushiBtw/discord-music-player#99]
Basically what the title suggests. Would love to see that feature. Ty in advance!

**Comment by SushiBtw** [comment]
We do support YouTube and Spotify links.
```js
Player#play(LinkOrString);
```

**Comment by Z3T4C0DE** [comment]
Returns with "No song with that query was found." using the client.player.play function.

**Comment by Z3T4C0DE** [comment]
` if (client.player.isPlaying(message)) {
                let song = await client.player.addToQueue(
                  message,
                  args.join(" ")
                );

                // If there were no errors the Player#songAdd event will fire and the song will not be null.
                if (song) return;
              } else {
                let song = await client.player.play(message, args.join(" "));

                // If there were no errors the Player#songAdd event will fire and the song will not be null.
                if (song) {
               message.channel.send(`${song.name} is now playing!`)
                }`

**Comment by SushiBtw** [comment]
Can you console.log `args.join(" ")`?

**Comment by Z3T4C0DE** [comment]
Oh yeah that's the problem. I found a bug tho. So if I disconnect my bot then play a song, it'll say that it is added in the queue but there's no audio coming. It doesn't play them. I made it so that it joins everytime I use the command to see.

**Comment by Z3T4C0DE** [comment]
I think the client.on("clientDisconnect") function doesn't work on my end that's why.

**Comment by Z3T4C0DE** [comment]
Yeah that's the issue. The bot doesn't trigger the clientDisconnect event

**Comment by SushiBtw** [comment]
**I fixed your issue and I will be pushing the update to NPM in ~4 hours.**
I will let you know, thanks for reporting!

**Comment by SushiBtw** [comment]
Hey! Update time!
I hope everything got fixed, please check within `v7.1.0` and let me know if the error still exists!
https://www.npmjs.com/package/discord-music-player

Thanks for reporting,
Sushi!

**Comment by Z3T4C0DE** [comment]
Yep. You fixed it. Thanks!
